{
  "hash": "87bbaf20b4011c0f019fc56341833d13",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"FEF_mulRegression_Tutorial\"\nsubtitle: \"Using single-neuron recordings data from macaque frontal eye field (FEF)\"\nauthor: \"Yujingai (Emmy) Shi\"\ndate: today\ndate-format: \"MMMM D, YYYY\"\nabstract: |\n  This tutorial aims to provide step-by-step instructions on multiple linear\n  regression in R; we are using a dataset of 316 single neurons recorded from\n  the frontal eye field (FEF) of two macaque monkeys.For the data, we employed \n  the linear probes with 128 channels to acquired them.\n  In this tutorial, we would walkthrough the exploratory analysis, \n  model fitting, assumption checking, and effect sizes, and a discussion on \n  alternative options.\n---\n\n\n\n# 1. Introduction\n\n## 1.1 What is multiple regression?\n\nLinear regression aims to predict one continuous outcome based on predictive variables. Simple linear regression models the relationship between the dependent variable and one predictor (\\(y = a + bx + e\\)). On the other hand, multiple regression introduces a more natural solution for complex real-life questions by asking how several predictors could jontly relate to the outcome. Therefore, the formula model for multiple regression is:\n$$\nY = \\beta_0 + \\beta_1 X_1 + \\beta_2 X_2 + \\cdots + \\beta_p X_p + \\varepsilon,\n$$\nIn this model, $Y$ is the dependent variable (predicted outcome), $X_i$ are the independent variables (predictors), $\\beta_0$ is the intercept, $\\beta_i$ represents the change in y given a one-unit change in the x variable while holding the other variables constant, and $\\varepsilon$ represents the error term. \n\n::: {.callout-note}\n## Why this matters\nA single predictor is important in determing the whole relationship, but if we zoom out, and we might found a lot other confounds. This is exactly what we found in real world: we can see tons of factors influencing the real outcome. From the Simpson's Paradox, we know that a trend observed in subgroups might disappear if we combine these groups. If we only look one variable, we might overlook other potential predictor's influence. Multiple regression helps us to  address this issue by allowing us to examine the contribution of each predictor while still controlling for others.\n:::\n\n## 1.2 The dataset: single neurons data in macaque Frontal Eye Field (FEF)\n\nThe frontal eye field (FEF) is an important region of prefrontal cortex involved in visual attention. In the past, we knew that it controls the voluntary and rapid eye movements, now we also know that it controls for covert attention without eye movements as well. Therefore, FEF contributes to the frontal-parietal connections works for primate visual attention.\n\nIn this dataset, we have extracellular single neuron recordings collected from two macaque monkeys under spatial attention tasks, in which we recorded the voltage changes of individual neurons while monkeys performed this task. \n\nWe got this dataset after spike sorting and manual curation, and we have high-quality, isolated neuron in this datset.For each of the neuron, we call it **unit**, and here is its metrics: \n\n| Variable | Meaning |\n|---|---|\n| `firing_rate` | Mean spike rate across the session in Hz |\n| `fano_factor` | Variance/mean of spike counts |\n| `cv_isi` | Coefficient of variation of inter-spike intervals |\n| `burst_index` | Tendency to fire in bursts |\n| `trough_to_peak` | The interval between the global minimum of the spike and the following peak |\n| `repolarization_time` | Time to capture how quickly the neuron returns to baseline |\n| `depth` | Depth of the recording electrode in µm |\n| `channel` | Recording channel number on the probe |\n| `n_spikes_unit` | Total spike count for the unit |\n| `session_duration_sec` | Length of the recording session |\n| `session_id` | Number for the recording session |\n| `unit_id` | Unit ID |\n\nIn summary, the full dataset has **316 units** distributed across **8 sessions** from **two monkeys**.\n\n::: {.callout-tip}\n## Note on cell-type\nThe two most important metrics here are trough to **peak duration** and **repolarization time** since they are used to define the cell types. Normally, there are roughly two cell types, **narrow-spiking interneurons** tend to have short trough to peak duration and fast repolarization time, while **broad-spiking excitatory neurons** tend to have longer trough to peak duration and slower repolarization time. Apart from these feature differences, the cell types tend to differ in firing properties as well.\n:::\n\n## 1.3 Our research question\n\n> **Do the waveform features (trough to peak duration and repolarization time) of a neuron predict how often it fires?**\n\nFrom this question, we will model `firing_rate` as a function of `trough_to_peak`, `repolarization_time`, and `depth`. The first two are waveform features that capture the cell-type info, and the `depth` is treated as a control, since the depth of the probe is known to influence baseline firing rates and we want to isolate the effect of waveform shape from other effect.\n\nTherefore, we aim to know in this tutorial that: \n\n1. Whether and potentially how these three predictors jointly relate to firing rate\n2. Whether the assumptions of OLS regression are appropriate here \n4. How to interpret and examine these results here (we would also have a small writeup)\n5. What alternatives here might also suit for my dataset\n\n# 2. Setup\n\n## 2.1 Loading packages\nWe will employ pacakges from the **tidyverse** to do plotting and data manipulation and the **easystats** to clean model summaries and effect sizes.\n\nSo we frist need to check whether each package is installed and then loads them all. \n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrequired_pkgs <- c(\n  \"tidyverse\",    \n  \"easystats\",     \n  \"performance\",   #check_model\n  \"parameters\",    \n  \"see\",          \n  \"correlation\",   \n  \"ggeffects\",     \n  \"gt\",            \n  \"broom\",         \n  \"patchwork\",    \n  \"car\",           \n  \"sandwich\",      \n  \"lmtest\",        \n  \"knitr\"\n)\n#install anything missing\nmissing_pkgs <- setdiff(required_pkgs, rownames(installed.packages()))\nif (length(missing_pkgs) > 0) {\n  install.packages(missing_pkgs, repos = \"https://cloud.r-project.org\")}\n\n#load\nsuppressPackageStartupMessages(\n  invisible(lapply(required_pkgs, library, character.only = TRUE))\n)\n\noptions(scipen = 999, digits = 4)\ntheme_set(theme_minimal(base_size = 12))\n```\n:::\n\n\n## 2.2 Loading the data\nThe data are stored as a CSV file; We need to load it with **read_csv** and have a quick look.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfef <- readr::read_csv(\"data/fef_prelim_metrics.csv\", show_col_types = FALSE)\n\nglimpse(fef)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 316\nColumns: 12\n$ session_id           <chr> \"2023-09-20_230920_140130\", \"2023-09-20_230920_14…\n$ unit_id              <dbl> 76, 94, 109, 248, 249, 257, 268, 271, 272, 274, 2…\n$ channel              <dbl> 46, 40, 34, 62, 62, 61, 60, 59, 58, 57, 56, 56, 5…\n$ depth                <dbl> 875, 1175, 1475, 75, 75, 125, 175, 225, 275, 325,…\n$ n_spikes_unit        <dbl> 42404, 324173, 141934, 18510, 69247, 142624, 2799…\n$ session_duration_sec <dbl> 10332, 10332, 10332, 10332, 10332, 10332, 10332, …\n$ trough_to_peak       <dbl> 0.1024, 0.2379, 0.3437, 0.7469, 0.7601, 0.1785, 0…\n$ repolarization_time  <dbl> 0.03635, 0.07931, 0.20489, 0.26768, 0.27429, 0.11…\n$ firing_rate          <dbl> 4.1041, 31.3752, 13.7371, 1.7915, 6.7021, 13.8039…\n$ fano_factor          <dbl> 1.292, 1.952, 3.415, 2.191, 1.744, 2.766, 2.669, …\n$ cv_isi               <dbl> 1.889, 1.656, 2.955, 4.007, 1.492, 2.163, 1.561, …\n$ burst_index          <dbl> 0.91262, 0.38318, 4.53866, 0.09088, 2.02452, 1.30…\n```\n\n\n:::\n:::\n\n\nWe can do some sanity checks:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n#dimension\ndim(fef)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 316  12\n```\n\n\n:::\n\n```{.r .cell-code}\n#number of units we have \nfef |>\n  count(session_id, name = \"n_units\") |>\n  knitr::kable(caption = \"Number of units recorded per session.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Number of units recorded per session.\n\n|session_id               | n_units|\n|:------------------------|-------:|\n|2023-09-20_230920_140130 |      38|\n|2023-09-21_230921_113113 |      33|\n|2023-09-23_230923_150303 |      54|\n|2023-09-24_230924_113501 |      30|\n|2024-03-27_240327_114515 |      56|\n|2024-04-06_240406_132530 |      40|\n|2024-04-08_240408_123252 |      39|\n|2024-04-09_240409_134911 |      26|\n\n\n:::\n\n```{.r .cell-code}\n#check missing values; (normally due to the data traits we assume none)\ncolSums(is.na(fef))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          session_id              unit_id              channel \n                   0                    0                    0 \n               depth        n_spikes_unit session_duration_sec \n                   0                    0                    0 \n      trough_to_peak  repolarization_time          firing_rate \n                   0                    0                    0 \n         fano_factor               cv_isi          burst_index \n                   0                    0                    0 \n```\n\n\n:::\n:::\n\n::: {.callout-note}\n## About the data\n- So we confirmed that we  have **316 units** across **8 sessions**\n- The number of units per session ranges is around 30-50 unit\n- There are no missing values \n:::\n\n# 3. Exploratory Data Analysis\nBefore fitting any model, we can first see the  distributions of each variable and pairwise relationships so we can have an understanding of how we can model it later :)\n\n## 3.1 Distributions of the features\n\nWe focus on the four variables: the outcome **firing_rate** and the three predictors **trough_to_peak**, **repolarization_time**, and **depth**.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfef_long <- fef |>\n  select(firing_rate, trough_to_peak, repolarization_time, depth) |>\n  pivot_longer(everything(), names_to = \"variable\", values_to = \"value\")\n\nggplot(fef_long, aes(x = value)) +\n  geom_histogram(bins = 30, fill = \"#1f8a8c\", color = \"white\", alpha = 0.8) +\n  facet_wrap(~ variable, scales = \"free\", ncol = 3) +\n  labs(\n    x = NULL, y = \"Number of units\",\n    title = \"Distributions of features\"\n  )\n```\n\n::: {.cell-output-display}\n![](FEF_mulRegression_Tutorial_files/figure-html/distributions-1.png){fig-align='center' width=1050}\n:::\n:::\n\n::: {.callout-note}\n## What we found\n1. **`firing_rate` is strongly right-skewed.** \n2. **`trough_to_peak` is bimodal.** This suggest there are two potential cell types here as we mentioned earlier.\n:::\n\n## 3.2 Correlations\n\nWe can first check how the predictors may correlate with each other by having a correlation matrix since multiple regression does not expect predictors to be so tightly correlated (but could have some slight correlations).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfef |>\n  select(firing_rate, trough_to_peak, repolarization_time, depth) |>\n  correlation::correlation() |>\n  summary(redundant = TRUE) |>\n  knitr::kable(digits = 2, caption = \"Pairwise Pearson correlations.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Pairwise Pearson correlations.\n\n|Parameter           | firing_rate| trough_to_peak| repolarization_time| depth|\n|:-------------------|-----------:|--------------:|-------------------:|-----:|\n|firing_rate         |        1.00|           0.23|                0.39| -0.18|\n|trough_to_peak      |        0.23|           1.00|                0.53| -0.10|\n|repolarization_time |        0.39|           0.53|                1.00| -0.05|\n|depth               |       -0.18|          -0.10|               -0.05|  1.00|\n\n\n:::\n:::\n\n\n::: {.callout-note}\n## Correlatons\n- **All of the three predictors have some correlations with the outcome**, with repolarization time the strongest, but the extent is moderate, so we could see each of the predictor contribute to some correlation with the outcome.\n- **The two waveform-shape variables correlate with each other with moderately strong  r = 0.53**, which is biologically reasonable. \n- **Depth** is a great control here since it weakly correlate with the two waveform features \n:::\n\n## 3.3 Bivariate relationships with the outcome\nWe can see from the scatterplot to show whether we can see linear patterns.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\np1 <- ggplot(fef, aes(trough_to_peak, firing_rate)) +\n  geom_point(alpha = 0.5, color = \"#1f8a8c\") +\n  geom_smooth(method = \"lm\", se = TRUE, color = \"#d97706\") +\n  labs(x = \"Trough-to-peak (ms)\", y = \"Firing rate (Hz)\")\n\np2 <- ggplot(fef, aes(repolarization_time, firing_rate)) +\n  geom_point(alpha = 0.5, color = \"#1f8a8c\") +\n  geom_smooth(method = \"lm\", se = TRUE, color = \"#d97706\") +\n  labs(x = \"Repolarization time (ms)\", y = \"Firing rate (Hz)\")\n\np3 <- ggplot(fef, aes(depth, firing_rate)) +\n  geom_point(alpha = 0.5, color = \"#1f8a8c\") +\n  geom_smooth(method = \"lm\", se = TRUE, color = \"#d97706\") +\n  labs(x = \"Depth (µm)\", y = \"Firing rate (Hz)\")\n\n(p1 | p2 | p3)\n```\n\n::: {.cell-output-display}\n![](FEF_mulRegression_Tutorial_files/figure-html/scatterplots-1.png){fig-align='center' width=1050}\n:::\n:::\n\n::: {.callout-note}\n## In the scatterplot\n- **The right-skew is very strong.** So we can see the `firing_rate` points are most near the bottom and a few of them at very hight herz,and this non-constant feature suggests that **homoskedasticity** (the assumption that residual variance is constant) would not true. We need to address it later. \n:::\n\n# 4. Fitting the multiple regression\n\n## 4.1 The model we will fit\n\nSpecifically, according to our plan, the model is like this: \n$$\n\\text{firing\\_rate} = \\beta_0 + \\beta_1\\,\\text{trough\\_to\\_peak} + \\beta_2\\,\\text{repolarization\\_time} + \\beta_3\\,\\text{depth} + \\varepsilon.\n$$\n\n## 4.2 Fitting the model\n\nWe fit a linear model with `lm()`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfit <- lm(firing_rate ~ trough_to_peak + repolarization_time + depth,\n          data = fef)\n\nfit\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = firing_rate ~ trough_to_peak + repolarization_time + \n    depth, data = fef)\n\nCoefficients:\n        (Intercept)       trough_to_peak  repolarization_time  \n            5.03122              0.31547             35.95989  \n              depth  \n           -0.00185  \n```\n\n\n:::\n:::\n\n## 4.3 Output\n\nWe can use `summary(fit)` to see the summarizing output. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nparameters::model_parameters(fit) |>\n  print()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nParameter           | Coefficient |       SE |         95% CI | t(312) |      p\n-------------------------------------------------------------------------------\n(Intercept)         |        5.03 |     1.77 | [ 1.54,  8.52] |   2.84 | 0.005 \ntrough to peak      |        0.32 |     2.24 | [-4.08,  4.71] |   0.14 | 0.888 \nrepolarization time |       35.96 |     5.82 | [24.50, 47.42] |   6.18 | < .001\ndepth               |   -1.85e-03 | 5.98e-04 | [ 0.00,  0.00] |  -3.09 | 0.002 \n```\n\n\n:::\n:::\n\nEach row of this table corresponds to one coefficient.\n\n- **Coefficient** \n- **CI low / CI high** — the 95% confidence interval \n- **t** — coefficient divided by its standard error.\n- **p** — the p-value for the null hypothesis \n\n::: {.callout-important}\n## What can we read from this model summary about the question we want to ask\n\n- **`trough_to_peak`** We can see from the coefficient and p value that if we control `repolarization_time` and `depth`, then one millisecond of increase in trough-to-peak duration provides no additional information about firing rate. The 95% CI [−4.08, 4.71] easily includes zero.\n\n**`repolarization_time`** Repolarization time shows the dominant effect. So we know that across the full observed range of repolarization time, predicted firing rate moves by roughly $35.96 \\times 0.5 \\approx 18$ Hz, while holding the other predictors constant.\n\n**Now from the summary we know that waveform shape predicts firing rate, but major predictive factor is specifically by `repolarization_time` instead of `trough_to_peak`. Depth contributes a small additional effect.**\n:::\n\n# 5. Checking Assumptions\n\nWe need to check the assumptions behind the OLS multiple regression model. The four assumptions are:\n\n1. **Linearity** — the relationship between each predictor and the outcome is linear.\n2. **Independence of errors** — residuals from one observation are not correlated with residuals from another.\n3. **Normality of residuals** — the residuals are roughly normally distributed.\n4. **Homoscedasticity** — residual variance is constant \n\nOther things like multicollinearity could also be checked here \n\n## 5.1 Plotting\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nperformance::check_model(fit)\n```\n\n::: {.cell-output-display}\n![](FEF_mulRegression_Tutorial_files/figure-html/check-model-1.png){fig-align='center' width=1350}\n:::\n:::\n\n\n::: {.callout-important}\nWalking through each assumption panel:\n\n- **Posterior predictive check** The green observed density is shifted right and get narrower than the blue density predicted by the model. The Gaussian assumption is a poor fit to this positive and  right-skewed outcome. So this suggest that we need to transform `firing_rate`later to handle it. \n- **Linearity**   Linearity itself is reasonable. \n- **Homogeneity of variance** Residual variance grows with the fitted value, so this show a very clear version of **heteroskedasticity** and is exactly matched what we thought may have from the right-skew in section 3.\n- **Influential observations** All points sit inside the Cook's-distance contours.\n- **Collinearity** All three predictors land in the \"Low (< 5)\" zone. Multicollinearity is not appearing to be a problem here. \n- **Normality of residuals**  The right tail have an upward trend. This is the predictable consequence of a right-skewed outcome and should improve substantially after a log transform.\n:::\n\n## 5.2 Multicollinearity \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nperformance::check_collinearity(fit)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Term\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"VIF\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"VIF_CI_low\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"VIF_CI_high\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"SE_factor\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Tolerance\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Tolerance_CI_low\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Tolerance_CI_high\"],\"name\":[8],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"trough_to_peak\",\"2\":\"1.412\",\"3\":\"1.255\",\"4\":\"1.665\",\"5\":\"1.188\",\"6\":\"0.7082\",\"7\":\"0.600741\",\"8\":\"0.7965\"},{\"1\":\"repolarization_time\",\"2\":\"1.400\",\"3\":\"1.246\",\"4\":\"1.650\",\"5\":\"1.183\",\"6\":\"0.7144\",\"7\":\"0.606079\",\"8\":\"0.8027\"},{\"1\":\"depth\",\"2\":\"1.011\",\"3\":\"1.000\",\"4\":\"209.579\",\"5\":\"1.006\",\"6\":\"0.9889\",\"7\":\"0.004771\",\"8\":\"1.0000\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n::: {.callout-important}\nThe VIF are all smaller than 5, all three predictors are inside the safe zone, so we dont wrroy about the multicollinearity problem here.\n:::\n\n## 5.3 Heteroskedasticity\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nperformance::check_heteroscedasticity(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWarning: Heteroscedasticity (non-constant error variance) detected (p < .001).\n```\n\n\n:::\n:::\n\nThis mataching the observations above. \n\n## 5.4 Normality of residuals\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nperformance::check_normality(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWarning: Non-normality of residuals detected (p < .001).\n```\n\n\n:::\n:::\n\nThis is matching the observations above. \n\n## 5.5 Independence\nIn this dataset, the 316 units come from only **8 sessions**. Units recorded in the same session share an animal, an electrode position, and a recording day, so their residuals are very likely correlated.The independence assumption is likely violated. \n\n\n::: {.callout-note}\n## Summary:\n\nThe checking assumptions show three problems\n- **Homoscedasticity** Violated,  Heteroscedasticity detected (p < .001) \n- **Normality of residuals** Violated, Shapiro–Wilk p < .001 \n- **Independence** Violated,316 units come from only 8 sessions \n\nThe first two violations is of the right-skewed outcome. A log transform of `firing_rate` should largely fix them.\nThe third (independence) variable, we  address it with **HC3 cluster-robust standard errors**, which keep the OLS point estimates but recompute the standard errors to acknowledge within-session correlation.\n:::\n\n# 6. Fixing the Violations\n\nSo we can the assumptions violated for **heteroscedasticity** and **non-normal residuals**. We now need to do a log transform for th firing rates to solve this problem. \n\n## 6.1 Log-transform the outcome\n\nFiring rates are right-skewed, so `log()` should stablizes variance.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm_log <- lm(log(firing_rate) ~ trough_to_peak + repolarization_time + depth,\n            data = fef)\n\ncheck_heteroscedasticity(m_log)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWarning: Heteroscedasticity (non-constant error variance) detected (p = 0.004).\n```\n\n\n:::\n\n```{.r .cell-code}\ncheck_normality(m_log)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWarning: Non-normality of residuals detected (p = 0.031).\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncheck_model(m_log, check = c(\"homogeneity\", \"qq\"))\n```\n\n::: {.cell-output-display}\n![](FEF_mulRegression_Tutorial_files/figure-html/unnamed-chunk-2-1.png){fig-align='center' width=1200}\n:::\n:::\n\n\n## 6.2 Cluster-robust SEs\n\nUnits are nested in 8 sessions, so residuals aren't independent. So we use HC3 to improve it.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(sandwich); library(lmtest)\n\ncoeftest(m_log, vcov = vcovCL(m_log, cluster = ~ session_id, type = \"HC3\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nt test of coefficients:\n\n                      Estimate Std. Error t value  Pr(>|t|)    \n(Intercept)          1.1445097  0.2986584    3.83   0.00015 ***\ntrough_to_peak       0.3585993  0.3912814    0.92   0.36013    \nrepolarization_time  4.3324937  1.0091417    4.29 0.0000235 ***\ndepth               -0.0003244  0.0000719   -4.51 0.0000092 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n::: {.callout-note}\n**Summary of the Violation Handle**\n\n- **Non-normality** — So we do the Log-transforming of the `firing_rate`, and we could see a lot of improvements. The QQ plot now tracks the reference line much better that previously, and although the violation check still returns p = .031, we could see the deviations are minor at this stage, so we largely fix this violations.\n\n- **Heteroscedasticity** — We can see a lot of improvements  after the log transform but we are not fully solve the problem of hereoscedasticity since we got (p = .004). I think the good point here is that the HC3 would provide robust inference even when residual variance isn't constant, so we might have less worry on this. But in the future, we might need to think other way to transfor firing rates to solve this issue entirely. \n\n- **Non-independence (8 sessions)** — We address this issue by clustering SE on `session_id`. Now we can see `repolarization_time` and `depth` remain highly significant and `trough_to_peak` stays non-significant, which is matching the original OLS conclusion.\n:::\n\n# 7. Effect Size and the Interpretation\n\n## 7.1 Model fit\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nr2(m_log)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# R2 for Linear Regression\n       R2: 0.292\n  adj. R2: 0.285\n```\n\n\n:::\n:::\n\n\n## 7.2 Standardized coefficients\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nparameters(m_log, standardize = \"refit\")\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Parameter\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Coefficient\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"SE\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"CI\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"CI_low\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"CI_high\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"t\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"df_error\"],\"name\":[8],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"p\"],\"name\":[9],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"(Intercept)\",\"2\":\"0.62126\",\"3\":\"0.02094\",\"4\":\"0.95\",\"5\":\"0.58006\",\"6\":\"0.66246\",\"7\":\"29.6712\",\"8\":\"312\",\"9\":\"0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000007717\"},{\"1\":\"trough_to_peak\",\"2\":\"0.01837\",\"3\":\"0.02492\",\"4\":\"0.95\",\"5\":\"-0.03066\",\"6\":\"0.06740\",\"7\":\"0.7372\",\"8\":\"312\",\"9\":\"0.461540122141547159984042991709429770708084106445312500000000000000000000000000000000000000000000\"},{\"1\":\"repolarization_time\",\"2\":\"0.17454\",\"3\":\"0.02481\",\"4\":\"0.95\",\"5\":\"0.12572\",\"6\":\"0.22336\",\"7\":\"7.0349\",\"8\":\"312\",\"9\":\"0.000000000012679609775125583022491639785268293869058275902261812007054686546325683593750000000000\"},{\"1\":\"depth\",\"2\":\"-0.09375\",\"3\":\"0.02109\",\"4\":\"0.95\",\"5\":\"-0.13524\",\"6\":\"-0.05225\",\"7\":\"-4.4454\",\"8\":\"312\",\"9\":\"0.000012208063903612227031245628106059797346460982225835323333740234375000000000000000000000000000\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n## 7.3 Partial effect sizes\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(effectsize)\neta_squared(car::Anova(m_log, type = 2), partial = TRUE)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Parameter\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Eta2_partial\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"CI\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"CI_low\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"CI_high\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"trough_to_peak\",\"2\":\"0.007763\",\"3\":\"0.95\",\"4\":\"0.00000\",\"5\":\"1\"},{\"1\":\"repolarization_time\",\"2\":\"0.144125\",\"3\":\"0.95\",\"4\":\"0.08927\",\"5\":\"1\"},{\"1\":\"depth\",\"2\":\"0.082125\",\"3\":\"0.95\",\"4\":\"0.03984\",\"5\":\"1\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n::: {.callout-note}\n- **Overall fit** — The three predictors jointly explain **29% of the variance** in log firing rate. This rate is actually pretty solide for neuron waveforms due to the noisy nature of the extracellular recordings and also we only have three waveform features in the model. \n- **Which predictor matters most?** \n  - `repolarization_time`: β = 0.17, $\\eta_p^2$ = .14, Now we can see the repolarization has the  **large** effect compared to the medium effect by depth and negligible effect from trough to peak duration. \n- Now we can see that longer repolarization times predict higher firing rates; and deeper units fire at lower rates. \n:::\n\n# 8. Visualizing Partial Effects\n\n## 8.1 Predicted firing rate vs. each predictor\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(ggeffects)\n\np1 <- plot(predict_response(m_log, \"trough_to_peak\")) +\n  labs(title = \"Trough-to-peak\", y = \"Predicted firing rate (Hz)\")\n\np2 <- plot(predict_response(m_log, \"repolarization_time\")) +\n  labs(title = \"Repolarization time\", y = NULL)\n\np3 <- plot(predict_response(m_log, \"depth\")) +\n  labs(title = \"Depth\", y = NULL)\n\np1 + p2 + p3\n```\n\n::: {.cell-output-display}\n![](FEF_mulRegression_Tutorial_files/figure-html/unnamed-chunk-7-1.png){fig-align='center' width=1500}\n:::\n:::\n\n::: {.callout-important}\n\n- **Trough-to-peak (left)** — The line slopes upward, but the CI band is wide enough,so the effect is statistically not very certain here.\n\n- **Repolarization time (middle)** We can see a steep upward curve with a tight CI. We can see the predicted firing rate rises from from ~3 Hz at the shortest repolarization times to ~30 Hz at the longest across the observed range. This is the dominant predictor.\n\n- **Depth (right)** — We can see a clear downward slope, it shows a real but smaller effect than repolarization time.\n:::\n\n# 9. Summary and Discussion\n\n## 9.1 Summary\n\nAcross 316 FEF units, three features jointly explained **29% of the variance** in firing rate (with the log-transform):\n\n- **Repolarization time** is the dominant predictor, so that means that the units with longer repolarization would fired faster.\n- **depth of the elerode** had a smaller negative effect \n- **Trough-to-peak duration** was non-significant once the other features were controlled, even though it correlated moderately with firing rate. \n\nSo answering the question is that the repolarization time, compared to the trough to peak duration, is a greater predictive factor of how often the neuron fires. \n\n## 9.2 When is multiple regression the right tool?\n\n- The outcome is continuous\n- When we have several predictors and want to know each one's *unique* contribution\n- Observations are roughly independent\n:::\n\n## 9.3 Some alternatives\n\nFor this dataset specifically, now we realized that a **mixed-effects model** with a random intercept by `session_id` would be the more appropriate and reasonable model fit here, since it would estimate session-level variability directly.\n\n## 9.4 \n::: {.callout-important}\n- Thank you for walking through this tutorial with me! And thank you Suyog for letting me have a chance to do such tutorial, it makes me explore new things and actually thinking more how I may use Quarto website for other things!\n:::\n------------------------------------------------------------------------\n\n\n",
    "supporting": [
      "FEF_mulRegression_Tutorial_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}