<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.24">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Yujingai (Emmy) Shi">
<meta name="dcterms.date" content="2026-05-03">

<title>FEF_mulRegression_Tutorial – FEF Multiple Regression Tutorial</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dc55a5b9e770e841cd82e46aadbfb9b0.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-c02a067d3f995134eb217b1cab01ce10.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<link href="site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet">
<script src="site_libs/pagedtable-1.1/js/pagedtable.js"></script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">FEF Multiple Regression Tutorial</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./FEF_mulRegression_Tutorial.html" aria-current="page"> 
<span class="menu-text">Tutorial</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/InterstellarShi/PSY504_Class_Project"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">1. Introduction</a>
  <ul class="collapse">
  <li><a href="#what-is-multiple-regression" id="toc-what-is-multiple-regression" class="nav-link" data-scroll-target="#what-is-multiple-regression">1.1 What is multiple regression?</a></li>
  <li><a href="#the-dataset-single-neurons-data-in-macaque-frontal-eye-field-fef" id="toc-the-dataset-single-neurons-data-in-macaque-frontal-eye-field-fef" class="nav-link" data-scroll-target="#the-dataset-single-neurons-data-in-macaque-frontal-eye-field-fef">1.2 The dataset: single neurons data in macaque Frontal Eye Field (FEF)</a></li>
  <li><a href="#our-research-question" id="toc-our-research-question" class="nav-link" data-scroll-target="#our-research-question">1.3 Our research question</a></li>
  </ul></li>
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup">2. Setup</a>
  <ul class="collapse">
  <li><a href="#loading-packages" id="toc-loading-packages" class="nav-link" data-scroll-target="#loading-packages">2.1 Loading packages</a></li>
  <li><a href="#loading-the-data" id="toc-loading-the-data" class="nav-link" data-scroll-target="#loading-the-data">2.2 Loading the data</a></li>
  </ul></li>
  <li><a href="#exploratory-data-analysis" id="toc-exploratory-data-analysis" class="nav-link" data-scroll-target="#exploratory-data-analysis">3. Exploratory Data Analysis</a>
  <ul class="collapse">
  <li><a href="#distributions-of-the-features" id="toc-distributions-of-the-features" class="nav-link" data-scroll-target="#distributions-of-the-features">3.1 Distributions of the features</a></li>
  <li><a href="#correlations" id="toc-correlations" class="nav-link" data-scroll-target="#correlations">3.2 Correlations</a></li>
  <li><a href="#bivariate-relationships-with-the-outcome" id="toc-bivariate-relationships-with-the-outcome" class="nav-link" data-scroll-target="#bivariate-relationships-with-the-outcome">3.3 Bivariate relationships with the outcome</a></li>
  </ul></li>
  <li><a href="#fitting-the-multiple-regression" id="toc-fitting-the-multiple-regression" class="nav-link" data-scroll-target="#fitting-the-multiple-regression">4. Fitting the multiple regression</a>
  <ul class="collapse">
  <li><a href="#the-model-we-will-fit" id="toc-the-model-we-will-fit" class="nav-link" data-scroll-target="#the-model-we-will-fit">4.1 The model we will fit</a></li>
  <li><a href="#fitting-the-model" id="toc-fitting-the-model" class="nav-link" data-scroll-target="#fitting-the-model">4.2 Fitting the model</a></li>
  <li><a href="#output" id="toc-output" class="nav-link" data-scroll-target="#output">4.3 Output</a></li>
  </ul></li>
  <li><a href="#checking-assumptions" id="toc-checking-assumptions" class="nav-link" data-scroll-target="#checking-assumptions">5. Checking Assumptions</a>
  <ul class="collapse">
  <li><a href="#plotting" id="toc-plotting" class="nav-link" data-scroll-target="#plotting">5.1 Plotting</a></li>
  <li><a href="#multicollinearity" id="toc-multicollinearity" class="nav-link" data-scroll-target="#multicollinearity">5.2 Multicollinearity</a></li>
  <li><a href="#heteroskedasticity" id="toc-heteroskedasticity" class="nav-link" data-scroll-target="#heteroskedasticity">5.3 Heteroskedasticity</a></li>
  <li><a href="#normality-of-residuals" id="toc-normality-of-residuals" class="nav-link" data-scroll-target="#normality-of-residuals">5.4 Normality of residuals</a></li>
  <li><a href="#independence" id="toc-independence" class="nav-link" data-scroll-target="#independence">5.5 Independence</a></li>
  </ul></li>
  <li><a href="#fixing-the-violations" id="toc-fixing-the-violations" class="nav-link" data-scroll-target="#fixing-the-violations">6. Fixing the Violations</a>
  <ul class="collapse">
  <li><a href="#log-transform-the-outcome" id="toc-log-transform-the-outcome" class="nav-link" data-scroll-target="#log-transform-the-outcome">6.1 Log-transform the outcome</a></li>
  <li><a href="#cluster-robust-ses" id="toc-cluster-robust-ses" class="nav-link" data-scroll-target="#cluster-robust-ses">6.2 Cluster-robust SEs</a></li>
  </ul></li>
  <li><a href="#effect-size-and-the-interpretation" id="toc-effect-size-and-the-interpretation" class="nav-link" data-scroll-target="#effect-size-and-the-interpretation">7. Effect Size and the Interpretation</a>
  <ul class="collapse">
  <li><a href="#model-fit" id="toc-model-fit" class="nav-link" data-scroll-target="#model-fit">7.1 Model fit</a></li>
  <li><a href="#standardized-coefficients" id="toc-standardized-coefficients" class="nav-link" data-scroll-target="#standardized-coefficients">7.2 Standardized coefficients</a></li>
  <li><a href="#partial-effect-sizes" id="toc-partial-effect-sizes" class="nav-link" data-scroll-target="#partial-effect-sizes">7.3 Partial effect sizes</a></li>
  </ul></li>
  <li><a href="#visualizing-partial-effects" id="toc-visualizing-partial-effects" class="nav-link" data-scroll-target="#visualizing-partial-effects">8. Visualizing Partial Effects</a>
  <ul class="collapse">
  <li><a href="#predicted-firing-rate-vs.-each-predictor" id="toc-predicted-firing-rate-vs.-each-predictor" class="nav-link" data-scroll-target="#predicted-firing-rate-vs.-each-predictor">8.1 Predicted firing rate vs.&nbsp;each predictor</a></li>
  </ul></li>
  <li><a href="#summary-and-discussion" id="toc-summary-and-discussion" class="nav-link" data-scroll-target="#summary-and-discussion">9. Summary and Discussion</a>
  <ul class="collapse">
  <li><a href="#summary-1" id="toc-summary-1" class="nav-link" data-scroll-target="#summary-1">9.1 Summary</a></li>
  <li><a href="#when-is-multiple-regression-the-right-tool" id="toc-when-is-multiple-regression-the-right-tool" class="nav-link" data-scroll-target="#when-is-multiple-regression-the-right-tool">9.2 When is multiple regression the right tool?</a></li>
  <li><a href="#some-alternatives" id="toc-some-alternatives" class="nav-link" data-scroll-target="#some-alternatives">9.3 Some alternatives</a></li>
  <li><a href="#section" id="toc-section" class="nav-link" data-scroll-target="#section">9.4</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">FEF_mulRegression_Tutorial</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
<p class="subtitle lead">Using single-neuron recordings data from macaque frontal eye field (FEF)</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Yujingai (Emmy) Shi </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 3, 2026</p>
    </div>
  </div>
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Abstract</div>
    <p>This tutorial aims to provide step-by-step instructions on multiple linear regression in R; we are using a dataset of 316 single neurons recorded from the frontal eye field (FEF) of two macaque monkeys.For the data, we employed the linear probes with 128 channels to acquired them. In this tutorial, we would walkthrough the exploratory analysis, model fitting, assumption checking, and effect sizes, and a discussion on alternative options.</p>
  </div>
</div>


</header>


<section id="introduction" class="level1">
<h1>1. Introduction</h1>
<section id="what-is-multiple-regression" class="level2">
<h2 class="anchored" data-anchor-id="what-is-multiple-regression">1.1 What is multiple regression?</h2>
<p>Linear regression aims to predict one continuous outcome based on predictive variables. Simple linear regression models the relationship between the dependent variable and one predictor ((y = a + bx + e)). On the other hand, multiple regression introduces a more natural solution for complex real-life questions by asking how several predictors could jontly relate to the outcome. Therefore, the formula model for multiple regression is: <span class="math display">\[
Y = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + \cdots + \beta_p X_p + \varepsilon,
\]</span> In this model, <span class="math inline">\(Y\)</span> is the dependent variable (predicted outcome), <span class="math inline">\(X_i\)</span> are the independent variables (predictors), <span class="math inline">\(\beta_0\)</span> is the intercept, <span class="math inline">\(\beta_i\)</span> represents the change in y given a one-unit change in the x variable while holding the other variables constant, and <span class="math inline">\(\varepsilon\)</span> represents the error term.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Why this matters
</div>
</div>
<div class="callout-body-container callout-body">
<p>A single predictor is important in determing the whole relationship, but if we zoom out, and we might found a lot other confounds. This is exactly what we found in real world: we can see tons of factors influencing the real outcome. From the Simpson’s Paradox, we know that a trend observed in subgroups might disappear if we combine these groups. If we only look one variable, we might overlook other potential predictor’s influence. Multiple regression helps us to address this issue by allowing us to examine the contribution of each predictor while still controlling for others.</p>
</div>
</div>
</section>
<section id="the-dataset-single-neurons-data-in-macaque-frontal-eye-field-fef" class="level2">
<h2 class="anchored" data-anchor-id="the-dataset-single-neurons-data-in-macaque-frontal-eye-field-fef">1.2 The dataset: single neurons data in macaque Frontal Eye Field (FEF)</h2>
<p>The frontal eye field (FEF) is an important region of prefrontal cortex involved in visual attention. In the past, we knew that it controls the voluntary and rapid eye movements, now we also know that it controls for covert attention without eye movements as well. Therefore, FEF contributes to the frontal-parietal connections works for primate visual attention.</p>
<p>In this dataset, we have extracellular single neuron recordings collected from two macaque monkeys under spatial attention tasks, in which we recorded the voltage changes of individual neurons while monkeys performed this task.</p>
<p>We got this dataset after spike sorting and manual curation, and we have high-quality, isolated neuron in this datset.For each of the neuron, we call it <strong>unit</strong>, and here is its metrics:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>firing_rate</code></td>
<td>Mean spike rate across the session in Hz</td>
</tr>
<tr class="even">
<td><code>fano_factor</code></td>
<td>Variance/mean of spike counts</td>
</tr>
<tr class="odd">
<td><code>cv_isi</code></td>
<td>Coefficient of variation of inter-spike intervals</td>
</tr>
<tr class="even">
<td><code>burst_index</code></td>
<td>Tendency to fire in bursts</td>
</tr>
<tr class="odd">
<td><code>trough_to_peak</code></td>
<td>The interval between the global minimum of the spike and the following peak</td>
</tr>
<tr class="even">
<td><code>repolarization_time</code></td>
<td>Time to capture how quickly the neuron returns to baseline</td>
</tr>
<tr class="odd">
<td><code>depth</code></td>
<td>Depth of the recording electrode in µm</td>
</tr>
<tr class="even">
<td><code>channel</code></td>
<td>Recording channel number on the probe</td>
</tr>
<tr class="odd">
<td><code>n_spikes_unit</code></td>
<td>Total spike count for the unit</td>
</tr>
<tr class="even">
<td><code>session_duration_sec</code></td>
<td>Length of the recording session</td>
</tr>
<tr class="odd">
<td><code>session_id</code></td>
<td>Number for the recording session</td>
</tr>
<tr class="even">
<td><code>unit_id</code></td>
<td>Unit ID</td>
</tr>
</tbody>
</table>
<p>In summary, the full dataset has <strong>316 units</strong> distributed across <strong>8 sessions</strong> from <strong>two monkeys</strong>.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Note on cell-type
</div>
</div>
<div class="callout-body-container callout-body">
<p>The two most important metrics here are trough to <strong>peak duration</strong> and <strong>repolarization time</strong> since they are used to define the cell types. Normally, there are roughly two cell types, <strong>narrow-spiking interneurons</strong> tend to have short trough to peak duration and fast repolarization time, while <strong>broad-spiking excitatory neurons</strong> tend to have longer trough to peak duration and slower repolarization time. Apart from these feature differences, the cell types tend to differ in firing properties as well.</p>
</div>
</div>
</section>
<section id="our-research-question" class="level2">
<h2 class="anchored" data-anchor-id="our-research-question">1.3 Our research question</h2>
<blockquote class="blockquote">
<p><strong>Do the waveform features (trough to peak duration and repolarization time) of a neuron predict how often it fires?</strong></p>
</blockquote>
<p>From this question, we will model <code>firing_rate</code> as a function of <code>trough_to_peak</code>, <code>repolarization_time</code>, and <code>depth</code>. The first two are waveform features that capture the cell-type info, and the <code>depth</code> is treated as a control, since the depth of the probe is known to influence baseline firing rates and we want to isolate the effect of waveform shape from other effect.</p>
<p>Therefore, we aim to know in this tutorial that:</p>
<ol type="1">
<li>Whether and potentially how these three predictors jointly relate to firing rate</li>
<li>Whether the assumptions of OLS regression are appropriate here</li>
<li>How to interpret and examine these results here (we would also have a small writeup)</li>
<li>What alternatives here might also suit for my dataset</li>
</ol>
</section>
</section>
<section id="setup" class="level1">
<h1>2. Setup</h1>
<section id="loading-packages" class="level2">
<h2 class="anchored" data-anchor-id="loading-packages">2.1 Loading packages</h2>
<p>We will employ pacakges from the <strong>tidyverse</strong> to do plotting and data manipulation and the <strong>easystats</strong> to clean model summaries and effect sizes.</p>
<p>So we frist need to check whether each package is installed and then loads them all.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>required_pkgs <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"tidyverse"</span>,    </span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"easystats"</span>,     </span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"performance"</span>,   <span class="co">#check_model</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"parameters"</span>,    </span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"see"</span>,          </span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"correlation"</span>,   </span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">"ggeffects"</span>,     </span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  <span class="st">"gt"</span>,            </span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  <span class="st">"broom"</span>,         </span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>  <span class="st">"patchwork"</span>,    </span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>  <span class="st">"car"</span>,           </span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>  <span class="st">"sandwich"</span>,      </span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>  <span class="st">"lmtest"</span>,        </span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>  <span class="st">"knitr"</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="co">#install anything missing</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>missing_pkgs <span class="ot">&lt;-</span> <span class="fu">setdiff</span>(required_pkgs, <span class="fu">rownames</span>(<span class="fu">installed.packages</span>()))</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">length</span>(missing_pkgs) <span class="sc">&gt;</span> <span class="dv">0</span>) {</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">install.packages</span>(missing_pkgs, <span class="at">repos =</span> <span class="st">"https://cloud.r-project.org"</span>)}</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="co">#load</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">invisible</span>(<span class="fu">lapply</span>(required_pkgs, library, <span class="at">character.only =</span> <span class="cn">TRUE</span>))</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">scipen =</span> <span class="dv">999</span>, <span class="at">digits =</span> <span class="dv">4</span>)</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(<span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">12</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="loading-the-data" class="level2">
<h2 class="anchored" data-anchor-id="loading-the-data">2.2 Loading the data</h2>
<p>The data are stored as a CSV file; We need to load it with <strong>read_csv</strong> and have a quick look.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>fef <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_csv</span>(<span class="st">"data/fef_prelim_metrics.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(fef)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 316
Columns: 12
$ session_id           &lt;chr&gt; "2023-09-20_230920_140130", "2023-09-20_230920_14…
$ unit_id              &lt;dbl&gt; 76, 94, 109, 248, 249, 257, 268, 271, 272, 274, 2…
$ channel              &lt;dbl&gt; 46, 40, 34, 62, 62, 61, 60, 59, 58, 57, 56, 56, 5…
$ depth                &lt;dbl&gt; 875, 1175, 1475, 75, 75, 125, 175, 225, 275, 325,…
$ n_spikes_unit        &lt;dbl&gt; 42404, 324173, 141934, 18510, 69247, 142624, 2799…
$ session_duration_sec &lt;dbl&gt; 10332, 10332, 10332, 10332, 10332, 10332, 10332, …
$ trough_to_peak       &lt;dbl&gt; 0.1024, 0.2379, 0.3437, 0.7469, 0.7601, 0.1785, 0…
$ repolarization_time  &lt;dbl&gt; 0.03635, 0.07931, 0.20489, 0.26768, 0.27429, 0.11…
$ firing_rate          &lt;dbl&gt; 4.1041, 31.3752, 13.7371, 1.7915, 6.7021, 13.8039…
$ fano_factor          &lt;dbl&gt; 1.292, 1.952, 3.415, 2.191, 1.744, 2.766, 2.669, …
$ cv_isi               &lt;dbl&gt; 1.889, 1.656, 2.955, 4.007, 1.492, 2.163, 1.561, …
$ burst_index          &lt;dbl&gt; 0.91262, 0.38318, 4.53866, 0.09088, 2.02452, 1.30…</code></pre>
</div>
</div>
<p>We can do some sanity checks:</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co">#dimension</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(fef)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 316  12</code></pre>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co">#number of units we have </span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>fef <span class="sc">|&gt;</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(session_id, <span class="at">name =</span> <span class="st">"n_units"</span>) <span class="sc">|&gt;</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="at">caption =</span> <span class="st">"Number of units recorded per session."</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Number of units recorded per session.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">session_id</th>
<th style="text-align: right;">n_units</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">2023-09-20_230920_140130</td>
<td style="text-align: right;">38</td>
</tr>
<tr class="even">
<td style="text-align: left;">2023-09-21_230921_113113</td>
<td style="text-align: right;">33</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2023-09-23_230923_150303</td>
<td style="text-align: right;">54</td>
</tr>
<tr class="even">
<td style="text-align: left;">2023-09-24_230924_113501</td>
<td style="text-align: right;">30</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2024-03-27_240327_114515</td>
<td style="text-align: right;">56</td>
</tr>
<tr class="even">
<td style="text-align: left;">2024-04-06_240406_132530</td>
<td style="text-align: right;">40</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2024-04-08_240408_123252</td>
<td style="text-align: right;">39</td>
</tr>
<tr class="even">
<td style="text-align: left;">2024-04-09_240409_134911</td>
<td style="text-align: right;">26</td>
</tr>
</tbody>
</table>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co">#check missing values; (normally due to the data traits we assume none)</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colSums</span>(<span class="fu">is.na</span>(fef))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>          session_id              unit_id              channel 
                   0                    0                    0 
               depth        n_spikes_unit session_duration_sec 
                   0                    0                    0 
      trough_to_peak  repolarization_time          firing_rate 
                   0                    0                    0 
         fano_factor               cv_isi          burst_index 
                   0                    0                    0 </code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>About the data
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>So we confirmed that we have <strong>316 units</strong> across <strong>8 sessions</strong></li>
<li>The number of units per session ranges is around 30-50 unit</li>
<li>There are no missing values</li>
</ul>
</div>
</div>
</section>
</section>
<section id="exploratory-data-analysis" class="level1">
<h1>3. Exploratory Data Analysis</h1>
<p>Before fitting any model, we can first see the distributions of each variable and pairwise relationships so we can have an understanding of how we can model it later :)</p>
<section id="distributions-of-the-features" class="level2">
<h2 class="anchored" data-anchor-id="distributions-of-the-features">3.1 Distributions of the features</h2>
<p>We focus on the four variables: the outcome <strong>firing_rate</strong> and the three predictors <strong>trough_to_peak</strong>, <strong>repolarization_time</strong>, and <strong>depth</strong>.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>fef_long <span class="ot">&lt;-</span> fef <span class="sc">|&gt;</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(firing_rate, trough_to_peak, repolarization_time, depth) <span class="sc">|&gt;</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="fu">everything</span>(), <span class="at">names_to =</span> <span class="st">"variable"</span>, <span class="at">values_to =</span> <span class="st">"value"</span>)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(fef_long, <span class="fu">aes</span>(<span class="at">x =</span> value)) <span class="sc">+</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">30</span>, <span class="at">fill =</span> <span class="st">"#1f8a8c"</span>, <span class="at">color =</span> <span class="st">"white"</span>, <span class="at">alpha =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> variable, <span class="at">scales =</span> <span class="st">"free"</span>, <span class="at">ncol =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">"Number of units"</span>,</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Distributions of features"</span></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="FEF_mulRegression_Tutorial_files/figure-html/distributions-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="1050"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>What we found
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li><strong><code>firing_rate</code> is strongly right-skewed.</strong></li>
<li><strong><code>trough_to_peak</code> is bimodal.</strong> This suggest there are two potential cell types here as we mentioned earlier.</li>
</ol>
</div>
</div>
</section>
<section id="correlations" class="level2">
<h2 class="anchored" data-anchor-id="correlations">3.2 Correlations</h2>
<p>We can first check how the predictors may correlate with each other by having a correlation matrix since multiple regression does not expect predictors to be so tightly correlated (but could have some slight correlations).</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>fef <span class="sc">|&gt;</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(firing_rate, trough_to_peak, repolarization_time, depth) <span class="sc">|&gt;</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  correlation<span class="sc">::</span><span class="fu">correlation</span>() <span class="sc">|&gt;</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>(<span class="at">redundant =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">2</span>, <span class="at">caption =</span> <span class="st">"Pairwise Pearson correlations."</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Pairwise Pearson correlations.</caption>
<colgroup>
<col style="width: 27%">
<col style="width: 16%">
<col style="width: 20%">
<col style="width: 27%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: right;">firing_rate</th>
<th style="text-align: right;">trough_to_peak</th>
<th style="text-align: right;">repolarization_time</th>
<th style="text-align: right;">depth</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">firing_rate</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">0.23</td>
<td style="text-align: right;">0.39</td>
<td style="text-align: right;">-0.18</td>
</tr>
<tr class="even">
<td style="text-align: left;">trough_to_peak</td>
<td style="text-align: right;">0.23</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">0.53</td>
<td style="text-align: right;">-0.10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">repolarization_time</td>
<td style="text-align: right;">0.39</td>
<td style="text-align: right;">0.53</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">-0.05</td>
</tr>
<tr class="even">
<td style="text-align: left;">depth</td>
<td style="text-align: right;">-0.18</td>
<td style="text-align: right;">-0.10</td>
<td style="text-align: right;">-0.05</td>
<td style="text-align: right;">1.00</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Correlatons
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong>All of the three predictors have some correlations with the outcome</strong>, with repolarization time the strongest, but the extent is moderate, so we could see each of the predictor contribute to some correlation with the outcome.</li>
<li><strong>The two waveform-shape variables correlate with each other with moderately strong r = 0.53</strong>, which is biologically reasonable.</li>
<li><strong>Depth</strong> is a great control here since it weakly correlate with the two waveform features</li>
</ul>
</div>
</div>
</section>
<section id="bivariate-relationships-with-the-outcome" class="level2">
<h2 class="anchored" data-anchor-id="bivariate-relationships-with-the-outcome">3.3 Bivariate relationships with the outcome</h2>
<p>We can see from the scatterplot to show whether we can see linear patterns.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(fef, <span class="fu">aes</span>(trough_to_peak, firing_rate)) <span class="sc">+</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">color =</span> <span class="st">"#1f8a8c"</span>) <span class="sc">+</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">"#d97706"</span>) <span class="sc">+</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Trough-to-peak (ms)"</span>, <span class="at">y =</span> <span class="st">"Firing rate (Hz)"</span>)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(fef, <span class="fu">aes</span>(repolarization_time, firing_rate)) <span class="sc">+</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">color =</span> <span class="st">"#1f8a8c"</span>) <span class="sc">+</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">"#d97706"</span>) <span class="sc">+</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Repolarization time (ms)"</span>, <span class="at">y =</span> <span class="st">"Firing rate (Hz)"</span>)</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>p3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(fef, <span class="fu">aes</span>(depth, firing_rate)) <span class="sc">+</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">color =</span> <span class="st">"#1f8a8c"</span>) <span class="sc">+</span></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">"#d97706"</span>) <span class="sc">+</span></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Depth (µm)"</span>, <span class="at">y =</span> <span class="st">"Firing rate (Hz)"</span>)</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>(p1 <span class="sc">|</span> p2 <span class="sc">|</span> p3)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="FEF_mulRegression_Tutorial_files/figure-html/scatterplots-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="1050"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>In the scatterplot
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong>The right-skew is very strong.</strong> So we can see the <code>firing_rate</code> points are most near the bottom and a few of them at very hight herz,and this non-constant feature suggests that <strong>homoskedasticity</strong> (the assumption that residual variance is constant) would not true. We need to address it later.</li>
</ul>
</div>
</div>
</section>
</section>
<section id="fitting-the-multiple-regression" class="level1">
<h1>4. Fitting the multiple regression</h1>
<section id="the-model-we-will-fit" class="level2">
<h2 class="anchored" data-anchor-id="the-model-we-will-fit">4.1 The model we will fit</h2>
<p>Specifically, according to our plan, the model is like this: <span class="math display">\[
\text{firing\_rate} = \beta_0 + \beta_1\,\text{trough\_to\_peak} + \beta_2\,\text{repolarization\_time} + \beta_3\,\text{depth} + \varepsilon.
\]</span></p>
</section>
<section id="fitting-the-model" class="level2">
<h2 class="anchored" data-anchor-id="fitting-the-model">4.2 Fitting the model</h2>
<p>We fit a linear model with <code>lm()</code>.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(firing_rate <span class="sc">~</span> trough_to_peak <span class="sc">+</span> repolarization_time <span class="sc">+</span> depth,</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>          <span class="at">data =</span> fef)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>fit</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = firing_rate ~ trough_to_peak + repolarization_time + 
    depth, data = fef)

Coefficients:
        (Intercept)       trough_to_peak  repolarization_time  
            5.03122              0.31547             35.95989  
              depth  
           -0.00185  </code></pre>
</div>
</div>
</section>
<section id="output" class="level2">
<h2 class="anchored" data-anchor-id="output">4.3 Output</h2>
<p>We can use <code>summary(fit)</code> to see the summarizing output.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>parameters<span class="sc">::</span><span class="fu">model_parameters</span>(fit) <span class="sc">|&gt;</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Parameter           | Coefficient |       SE |         95% CI | t(312) |      p
-------------------------------------------------------------------------------
(Intercept)         |        5.03 |     1.77 | [ 1.54,  8.52] |   2.84 | 0.005 
trough to peak      |        0.32 |     2.24 | [-4.08,  4.71] |   0.14 | 0.888 
repolarization time |       35.96 |     5.82 | [24.50, 47.42] |   6.18 | &lt; .001
depth               |   -1.85e-03 | 5.98e-04 | [ 0.00,  0.00] |  -3.09 | 0.002 </code></pre>
</div>
</div>
<p>Each row of this table corresponds to one coefficient.</p>
<ul>
<li><strong>Coefficient</strong></li>
<li><strong>CI low / CI high</strong> — the 95% confidence interval</li>
<li><strong>t</strong> — coefficient divided by its standard error.</li>
<li><strong>p</strong> — the p-value for the null hypothesis</li>
</ul>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>What can we read from this model summary about the question we want to ask
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong><code>trough_to_peak</code></strong> We can see from the coefficient and p value that if we control <code>repolarization_time</code> and <code>depth</code>, then one millisecond of increase in trough-to-peak duration provides no additional information about firing rate. The 95% CI [−4.08, 4.71] easily includes zero.</li>
</ul>
<p><strong><code>repolarization_time</code></strong> Repolarization time shows the dominant effect. So we know that across the full observed range of repolarization time, predicted firing rate moves by roughly <span class="math inline">\(35.96 \times 0.5 \approx 18\)</span> Hz, while holding the other predictors constant.</p>
<p><strong>Now from the summary we know that waveform shape predicts firing rate, but major predictive factor is specifically by <code>repolarization_time</code> instead of <code>trough_to_peak</code>. Depth contributes a small additional effect.</strong></p>
</div>
</div>
</section>
</section>
<section id="checking-assumptions" class="level1">
<h1>5. Checking Assumptions</h1>
<p>We need to check the assumptions behind the OLS multiple regression model. The four assumptions are:</p>
<ol type="1">
<li><strong>Linearity</strong> — the relationship between each predictor and the outcome is linear.</li>
<li><strong>Independence of errors</strong> — residuals from one observation are not correlated with residuals from another.</li>
<li><strong>Normality of residuals</strong> — the residuals are roughly normally distributed.</li>
<li><strong>Homoscedasticity</strong> — residual variance is constant</li>
</ol>
<p>Other things like multicollinearity could also be checked here</p>
<section id="plotting" class="level2">
<h2 class="anchored" data-anchor-id="plotting">5.1 Plotting</h2>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>performance<span class="sc">::</span><span class="fu">check_model</span>(fit)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="FEF_mulRegression_Tutorial_files/figure-html/check-model-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="1350"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>Walking through each assumption panel:</p>
<ul>
<li><strong>Posterior predictive check</strong> The green observed density is shifted right and get narrower than the blue density predicted by the model. The Gaussian assumption is a poor fit to this positive and right-skewed outcome. So this suggest that we need to transform <code>firing_rate</code>later to handle it.</li>
<li><strong>Linearity</strong> Linearity itself is reasonable.</li>
<li><strong>Homogeneity of variance</strong> Residual variance grows with the fitted value, so this show a very clear version of <strong>heteroskedasticity</strong> and is exactly matched what we thought may have from the right-skew in section 3.</li>
<li><strong>Influential observations</strong> All points sit inside the Cook’s-distance contours.</li>
<li><strong>Collinearity</strong> All three predictors land in the “Low (&lt; 5)” zone. Multicollinearity is not appearing to be a problem here.</li>
<li><strong>Normality of residuals</strong> The right tail have an upward trend. This is the predictable consequence of a right-skewed outcome and should improve substantially after a log transform.</li>
</ul>
</div>
</div>
</section>
<section id="multicollinearity" class="level2">
<h2 class="anchored" data-anchor-id="multicollinearity">5.2 Multicollinearity</h2>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>performance<span class="sc">::</span><span class="fu">check_collinearity</span>(fit)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["Term"],"name":[1],"type":["chr"],"align":["left"]},{"label":["VIF"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["VIF_CI_low"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["VIF_CI_high"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["SE_factor"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["Tolerance"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["Tolerance_CI_low"],"name":[7],"type":["dbl"],"align":["right"]},{"label":["Tolerance_CI_high"],"name":[8],"type":["dbl"],"align":["right"]}],"data":[{"1":"trough_to_peak","2":"1.412","3":"1.255","4":"1.665","5":"1.188","6":"0.7082","7":"0.600741","8":"0.7965"},{"1":"repolarization_time","2":"1.400","3":"1.246","4":"1.650","5":"1.183","6":"0.7144","7":"0.606079","8":"0.8027"},{"1":"depth","2":"1.011","3":"1.000","4":"209.579","5":"1.006","6":"0.9889","7":"0.004771","8":"1.0000"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>The VIF are all smaller than 5, all three predictors are inside the safe zone, so we dont wrroy about the multicollinearity problem here.</p>
</div>
</div>
</section>
<section id="heteroskedasticity" class="level2">
<h2 class="anchored" data-anchor-id="heteroskedasticity">5.3 Heteroskedasticity</h2>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>performance<span class="sc">::</span><span class="fu">check_heteroscedasticity</span>(fit)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Warning: Heteroscedasticity (non-constant error variance) detected (p &lt; .001).</code></pre>
</div>
</div>
<p>This mataching the observations above.</p>
</section>
<section id="normality-of-residuals" class="level2">
<h2 class="anchored" data-anchor-id="normality-of-residuals">5.4 Normality of residuals</h2>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>performance<span class="sc">::</span><span class="fu">check_normality</span>(fit)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Warning: Non-normality of residuals detected (p &lt; .001).</code></pre>
</div>
</div>
<p>This is matching the observations above.</p>
</section>
<section id="independence" class="level2">
<h2 class="anchored" data-anchor-id="independence">5.5 Independence</h2>
<p>In this dataset, the 316 units come from only <strong>8 sessions</strong>. Units recorded in the same session share an animal, an electrode position, and a recording day, so their residuals are very likely correlated.The independence assumption is likely violated.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Summary:
</div>
</div>
<div class="callout-body-container callout-body">
<p>The checking assumptions show three problems - <strong>Homoscedasticity</strong> Violated, Heteroscedasticity detected (p &lt; .001) - <strong>Normality of residuals</strong> Violated, Shapiro–Wilk p &lt; .001 - <strong>Independence</strong> Violated,316 units come from only 8 sessions</p>
<p>The first two violations is of the right-skewed outcome. A log transform of <code>firing_rate</code> should largely fix them. The third (independence) variable, we address it with <strong>HC3 cluster-robust standard errors</strong>, which keep the OLS point estimates but recompute the standard errors to acknowledge within-session correlation.</p>
</div>
</div>
</section>
</section>
<section id="fixing-the-violations" class="level1">
<h1>6. Fixing the Violations</h1>
<p>So we can the assumptions violated for <strong>heteroscedasticity</strong> and <strong>non-normal residuals</strong>. We now need to do a log transform for th firing rates to solve this problem.</p>
<section id="log-transform-the-outcome" class="level2">
<h2 class="anchored" data-anchor-id="log-transform-the-outcome">6.1 Log-transform the outcome</h2>
<p>Firing rates are right-skewed, so <code>log()</code> should stablizes variance.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>m_log <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(firing_rate) <span class="sc">~</span> trough_to_peak <span class="sc">+</span> repolarization_time <span class="sc">+</span> depth,</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> fef)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="fu">check_heteroscedasticity</span>(m_log)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Warning: Heteroscedasticity (non-constant error variance) detected (p = 0.004).</code></pre>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_normality</span>(m_log)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Warning: Non-normality of residuals detected (p = 0.031).</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_model</span>(m_log, <span class="at">check =</span> <span class="fu">c</span>(<span class="st">"homogeneity"</span>, <span class="st">"qq"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="FEF_mulRegression_Tutorial_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="1200"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="cluster-robust-ses" class="level2">
<h2 class="anchored" data-anchor-id="cluster-robust-ses">6.2 Cluster-robust SEs</h2>
<p>Units are nested in 8 sessions, so residuals aren’t independent. So we use HC3 to improve it.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sandwich); <span class="fu">library</span>(lmtest)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="fu">coeftest</span>(m_log, <span class="at">vcov =</span> <span class="fu">vcovCL</span>(m_log, <span class="at">cluster =</span> <span class="sc">~</span> session_id, <span class="at">type =</span> <span class="st">"HC3"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
t test of coefficients:

                      Estimate Std. Error t value  Pr(&gt;|t|)    
(Intercept)          1.1445097  0.2986584    3.83   0.00015 ***
trough_to_peak       0.3585993  0.3912814    0.92   0.36013    
repolarization_time  4.3324937  1.0091417    4.29 0.0000235 ***
depth               -0.0003244  0.0000719   -4.51 0.0000092 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Summary of the Violation Handle</strong></p>
<ul>
<li><p><strong>Non-normality</strong> — So we do the Log-transforming of the <code>firing_rate</code>, and we could see a lot of improvements. The QQ plot now tracks the reference line much better that previously, and although the violation check still returns p = .031, we could see the deviations are minor at this stage, so we largely fix this violations.</p></li>
<li><p><strong>Heteroscedasticity</strong> — We can see a lot of improvements after the log transform but we are not fully solve the problem of hereoscedasticity since we got (p = .004). I think the good point here is that the HC3 would provide robust inference even when residual variance isn’t constant, so we might have less worry on this. But in the future, we might need to think other way to transfor firing rates to solve this issue entirely.</p></li>
<li><p><strong>Non-independence (8 sessions)</strong> — We address this issue by clustering SE on <code>session_id</code>. Now we can see <code>repolarization_time</code> and <code>depth</code> remain highly significant and <code>trough_to_peak</code> stays non-significant, which is matching the original OLS conclusion.</p></li>
</ul>
</div>
</div>
</section>
</section>
<section id="effect-size-and-the-interpretation" class="level1">
<h1>7. Effect Size and the Interpretation</h1>
<section id="model-fit" class="level2">
<h2 class="anchored" data-anchor-id="model-fit">7.1 Model fit</h2>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">r2</span>(m_log)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># R2 for Linear Regression
       R2: 0.292
  adj. R2: 0.285</code></pre>
</div>
</div>
</section>
<section id="standardized-coefficients" class="level2">
<h2 class="anchored" data-anchor-id="standardized-coefficients">7.2 Standardized coefficients</h2>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">parameters</span>(m_log, <span class="at">standardize =</span> <span class="st">"refit"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["Parameter"],"name":[1],"type":["chr"],"align":["left"]},{"label":["Coefficient"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["SE"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["CI"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["CI_low"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["CI_high"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["t"],"name":[7],"type":["dbl"],"align":["right"]},{"label":["df_error"],"name":[8],"type":["int"],"align":["right"]},{"label":["p"],"name":[9],"type":["dbl"],"align":["right"]}],"data":[{"1":"(Intercept)","2":"0.62126","3":"0.02094","4":"0.95","5":"0.58006","6":"0.66246","7":"29.6712","8":"312","9":"0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000007717"},{"1":"trough_to_peak","2":"0.01837","3":"0.02492","4":"0.95","5":"-0.03066","6":"0.06740","7":"0.7372","8":"312","9":"0.461540122141547159984042991709429770708084106445312500000000000000000000000000000000000000000000"},{"1":"repolarization_time","2":"0.17454","3":"0.02481","4":"0.95","5":"0.12572","6":"0.22336","7":"7.0349","8":"312","9":"0.000000000012679609775125583022491639785268293869058275902261812007054686546325683593750000000000"},{"1":"depth","2":"-0.09375","3":"0.02109","4":"0.95","5":"-0.13524","6":"-0.05225","7":"-4.4454","8":"312","9":"0.000012208063903612227031245628106059797346460982225835323333740234375000000000000000000000000000"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
</section>
<section id="partial-effect-sizes" class="level2">
<h2 class="anchored" data-anchor-id="partial-effect-sizes">7.3 Partial effect sizes</h2>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(effectsize)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">eta_squared</span>(car<span class="sc">::</span><span class="fu">Anova</span>(m_log, <span class="at">type =</span> <span class="dv">2</span>), <span class="at">partial =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["Parameter"],"name":[1],"type":["chr"],"align":["left"]},{"label":["Eta2_partial"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["CI"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["CI_low"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["CI_high"],"name":[5],"type":["dbl"],"align":["right"]}],"data":[{"1":"trough_to_peak","2":"0.007763","3":"0.95","4":"0.00000","5":"1"},{"1":"repolarization_time","2":"0.144125","3":"0.95","4":"0.08927","5":"1"},{"1":"depth","2":"0.082125","3":"0.95","4":"0.03984","5":"1"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong>Overall fit</strong> — The three predictors jointly explain <strong>29% of the variance</strong> in log firing rate. This rate is actually pretty solide for neuron waveforms due to the noisy nature of the extracellular recordings and also we only have three waveform features in the model.</li>
<li><strong>Which predictor matters most?</strong>
<ul>
<li><code>repolarization_time</code>: β = 0.17, <span class="math inline">\(\eta_p^2\)</span> = .14, Now we can see the repolarization has the <strong>large</strong> effect compared to the medium effect by depth and negligible effect from trough to peak duration.</li>
</ul></li>
<li>Now we can see that longer repolarization times predict higher firing rates; and deeper units fire at lower rates.</li>
</ul>
</div>
</div>
</section>
</section>
<section id="visualizing-partial-effects" class="level1">
<h1>8. Visualizing Partial Effects</h1>
<section id="predicted-firing-rate-vs.-each-predictor" class="level2">
<h2 class="anchored" data-anchor-id="predicted-firing-rate-vs.-each-predictor">8.1 Predicted firing rate vs.&nbsp;each predictor</h2>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggeffects)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">plot</span>(<span class="fu">predict_response</span>(m_log, <span class="st">"trough_to_peak"</span>)) <span class="sc">+</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Trough-to-peak"</span>, <span class="at">y =</span> <span class="st">"Predicted firing rate (Hz)"</span>)</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">plot</span>(<span class="fu">predict_response</span>(m_log, <span class="st">"repolarization_time"</span>)) <span class="sc">+</span></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Repolarization time"</span>, <span class="at">y =</span> <span class="cn">NULL</span>)</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>p3 <span class="ot">&lt;-</span> <span class="fu">plot</span>(<span class="fu">predict_response</span>(m_log, <span class="st">"depth"</span>)) <span class="sc">+</span></span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Depth"</span>, <span class="at">y =</span> <span class="cn">NULL</span>)</span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a>p1 <span class="sc">+</span> p2 <span class="sc">+</span> p3</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="FEF_mulRegression_Tutorial_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="1500"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p><strong>Trough-to-peak (left)</strong> — The line slopes upward, but the CI band is wide enough,so the effect is statistically not very certain here.</p></li>
<li><p><strong>Repolarization time (middle)</strong> We can see a steep upward curve with a tight CI. We can see the predicted firing rate rises from from ~3 Hz at the shortest repolarization times to ~30 Hz at the longest across the observed range. This is the dominant predictor.</p></li>
<li><p><strong>Depth (right)</strong> — We can see a clear downward slope, it shows a real but smaller effect than repolarization time.</p></li>
</ul>
</div>
</div>
</section>
</section>
<section id="summary-and-discussion" class="level1">
<h1>9. Summary and Discussion</h1>
<section id="summary-1" class="level2">
<h2 class="anchored" data-anchor-id="summary-1">9.1 Summary</h2>
<p>Across 316 FEF units, three features jointly explained <strong>29% of the variance</strong> in firing rate (with the log-transform):</p>
<ul>
<li><strong>Repolarization time</strong> is the dominant predictor, so that means that the units with longer repolarization would fired faster.</li>
<li><strong>depth of the elerode</strong> had a smaller negative effect</li>
<li><strong>Trough-to-peak duration</strong> was non-significant once the other features were controlled, even though it correlated moderately with firing rate.</li>
</ul>
<p>So answering the question is that the repolarization time, compared to the trough to peak duration, is a greater predictive factor of how often the neuron fires.</p>
</section>
<section id="when-is-multiple-regression-the-right-tool" class="level2">
<h2 class="anchored" data-anchor-id="when-is-multiple-regression-the-right-tool">9.2 When is multiple regression the right tool?</h2>
<ul>
<li>The outcome is continuous</li>
<li>When we have several predictors and want to know each one’s <em>unique</em> contribution</li>
<li>Observations are roughly independent :::</li>
</ul>
</section>
<section id="some-alternatives" class="level2">
<h2 class="anchored" data-anchor-id="some-alternatives">9.3 Some alternatives</h2>
<p>For this dataset specifically, now we realized that a <strong>mixed-effects model</strong> with a random intercept by <code>session_id</code> would be the more appropriate and reasonable model fit here, since it would estimate session-level variability directly.</p>
</section>
<section id="section" class="level2">
<h2 class="anchored" data-anchor-id="section">9.4</h2>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Thank you for walking through this tutorial with me! And thank you Suyog for letting me have a chance to do such tutorial, it makes me explore new things and actually thinking more how I may use Quarto website for other things!</li>
</ul>
</div>
</div>
<hr>


<!-- -->

</section>
</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb34" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "FEF_mulRegression_Tutorial"</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="an">subtitle:</span><span class="co"> "Using single-neuron recordings data from macaque frontal eye field (FEF)"</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Yujingai (Emmy) Shi"</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> today</span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a><span class="an">date-format:</span><span class="co"> "MMMM D, YYYY"</span></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a><span class="an">abstract:</span><span class="co"> |</span></span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a><span class="co">  This tutorial aims to provide step-by-step instructions on multiple linear</span></span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a><span class="co">  regression in R; we are using a dataset of 316 single neurons recorded from</span></span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a><span class="co">  the frontal eye field (FEF) of two macaque monkeys.For the data, we employed </span></span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a><span class="co">  the linear probes with 128 channels to acquired them.</span></span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a><span class="co">  In this tutorial, we would walkthrough the exploratory analysis, </span></span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a><span class="co">  model fitting, assumption checking, and effect sizes, and a discussion on </span></span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a><span class="co">  alternative options.</span></span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-17"><a href="#cb34-17" aria-hidden="true" tabindex="-1"></a><span class="in">```{r setup}</span></span>
<span id="cb34-18"><a href="#cb34-18" aria-hidden="true" tabindex="-1"></a><span class="co">#| include: false</span></span>
<span id="cb34-19"><a href="#cb34-19" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(</span>
<span id="cb34-20"><a href="#cb34-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">echo =</span> <span class="cn">TRUE</span>,</span>
<span id="cb34-21"><a href="#cb34-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">warning =</span> <span class="cn">FALSE</span>,</span>
<span id="cb34-22"><a href="#cb34-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">message =</span> <span class="cn">FALSE</span>,</span>
<span id="cb34-23"><a href="#cb34-23" aria-hidden="true" tabindex="-1"></a>  <span class="at">fig.align =</span> <span class="st">"center"</span>,</span>
<span id="cb34-24"><a href="#cb34-24" aria-hidden="true" tabindex="-1"></a>  <span class="at">dpi =</span> <span class="dv">150</span></span>
<span id="cb34-25"><a href="#cb34-25" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb34-26"><a href="#cb34-26" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb34-27"><a href="#cb34-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-28"><a href="#cb34-28" aria-hidden="true" tabindex="-1"></a><span class="fu"># 1. Introduction</span></span>
<span id="cb34-29"><a href="#cb34-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-30"><a href="#cb34-30" aria-hidden="true" tabindex="-1"></a><span class="fu">## 1.1 What is multiple regression?</span></span>
<span id="cb34-31"><a href="#cb34-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-32"><a href="#cb34-32" aria-hidden="true" tabindex="-1"></a>Linear regression aims to predict one continuous outcome based on predictive variables. Simple linear regression models the relationship between the dependent variable and one predictor (<span class="sc">\(</span>y = a + bx + e<span class="sc">\)</span>). On the other hand, multiple regression introduces a more natural solution for complex real-life questions by asking how several predictors could jontly relate to the outcome. Therefore, the formula model for multiple regression is:</span>
<span id="cb34-33"><a href="#cb34-33" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb34-34"><a href="#cb34-34" aria-hidden="true" tabindex="-1"></a>Y = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + \cdots + \beta_p X_p + \varepsilon,</span>
<span id="cb34-35"><a href="#cb34-35" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb34-36"><a href="#cb34-36" aria-hidden="true" tabindex="-1"></a>In this model, $Y$ is the dependent variable (predicted outcome), $X_i$ are the independent variables (predictors), $\beta_0$ is the intercept, $\beta_i$ represents the change in y given a one-unit change in the x variable while holding the other variables constant, and $\varepsilon$ represents the error term. </span>
<span id="cb34-37"><a href="#cb34-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-38"><a href="#cb34-38" aria-hidden="true" tabindex="-1"></a>::: {.callout-note}</span>
<span id="cb34-39"><a href="#cb34-39" aria-hidden="true" tabindex="-1"></a><span class="fu">## Why this matters</span></span>
<span id="cb34-40"><a href="#cb34-40" aria-hidden="true" tabindex="-1"></a>A single predictor is important in determing the whole relationship, but if we zoom out, and we might found a lot other confounds. This is exactly what we found in real world: we can see tons of factors influencing the real outcome. From the Simpson's Paradox, we know that a trend observed in subgroups might disappear if we combine these groups. If we only look one variable, we might overlook other potential predictor's influence. Multiple regression helps us to  address this issue by allowing us to examine the contribution of each predictor while still controlling for others.</span>
<span id="cb34-41"><a href="#cb34-41" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb34-42"><a href="#cb34-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-43"><a href="#cb34-43" aria-hidden="true" tabindex="-1"></a><span class="fu">## 1.2 The dataset: single neurons data in macaque Frontal Eye Field (FEF)</span></span>
<span id="cb34-44"><a href="#cb34-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-45"><a href="#cb34-45" aria-hidden="true" tabindex="-1"></a>The frontal eye field (FEF) is an important region of prefrontal cortex involved in visual attention. In the past, we knew that it controls the voluntary and rapid eye movements, now we also know that it controls for covert attention without eye movements as well. Therefore, FEF contributes to the frontal-parietal connections works for primate visual attention.</span>
<span id="cb34-46"><a href="#cb34-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-47"><a href="#cb34-47" aria-hidden="true" tabindex="-1"></a>In this dataset, we have extracellular single neuron recordings collected from two macaque monkeys under spatial attention tasks, in which we recorded the voltage changes of individual neurons while monkeys performed this task. </span>
<span id="cb34-48"><a href="#cb34-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-49"><a href="#cb34-49" aria-hidden="true" tabindex="-1"></a>We got this dataset after spike sorting and manual curation, and we have high-quality, isolated neuron in this datset.For each of the neuron, we call it **unit**, and here is its metrics: </span>
<span id="cb34-50"><a href="#cb34-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-51"><a href="#cb34-51" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Variable <span class="pp">|</span> Meaning <span class="pp">|</span></span>
<span id="cb34-52"><a href="#cb34-52" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|</span></span>
<span id="cb34-53"><a href="#cb34-53" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`firing_rate`</span> <span class="pp">|</span> Mean spike rate across the session in Hz <span class="pp">|</span></span>
<span id="cb34-54"><a href="#cb34-54" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`fano_factor`</span> <span class="pp">|</span> Variance/mean of spike counts <span class="pp">|</span></span>
<span id="cb34-55"><a href="#cb34-55" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`cv_isi`</span> <span class="pp">|</span> Coefficient of variation of inter-spike intervals <span class="pp">|</span></span>
<span id="cb34-56"><a href="#cb34-56" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`burst_index`</span> <span class="pp">|</span> Tendency to fire in bursts <span class="pp">|</span></span>
<span id="cb34-57"><a href="#cb34-57" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`trough_to_peak`</span> <span class="pp">|</span> The interval between the global minimum of the spike and the following peak <span class="pp">|</span></span>
<span id="cb34-58"><a href="#cb34-58" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`repolarization_time`</span> <span class="pp">|</span> Time to capture how quickly the neuron returns to baseline <span class="pp">|</span></span>
<span id="cb34-59"><a href="#cb34-59" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`depth`</span> <span class="pp">|</span> Depth of the recording electrode in µm <span class="pp">|</span></span>
<span id="cb34-60"><a href="#cb34-60" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`channel`</span> <span class="pp">|</span> Recording channel number on the probe <span class="pp">|</span></span>
<span id="cb34-61"><a href="#cb34-61" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`n_spikes_unit`</span> <span class="pp">|</span> Total spike count for the unit <span class="pp">|</span></span>
<span id="cb34-62"><a href="#cb34-62" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`session_duration_sec`</span> <span class="pp">|</span> Length of the recording session <span class="pp">|</span></span>
<span id="cb34-63"><a href="#cb34-63" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`session_id`</span> <span class="pp">|</span> Number for the recording session <span class="pp">|</span></span>
<span id="cb34-64"><a href="#cb34-64" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`unit_id`</span> <span class="pp">|</span> Unit ID <span class="pp">|</span></span>
<span id="cb34-65"><a href="#cb34-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-66"><a href="#cb34-66" aria-hidden="true" tabindex="-1"></a>In summary, the full dataset has **316 units** distributed across **8 sessions** from **two monkeys**.</span>
<span id="cb34-67"><a href="#cb34-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-68"><a href="#cb34-68" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip}</span>
<span id="cb34-69"><a href="#cb34-69" aria-hidden="true" tabindex="-1"></a><span class="fu">## Note on cell-type</span></span>
<span id="cb34-70"><a href="#cb34-70" aria-hidden="true" tabindex="-1"></a>The two most important metrics here are trough to **peak duration** and **repolarization time** since they are used to define the cell types. Normally, there are roughly two cell types, **narrow-spiking interneurons** tend to have short trough to peak duration and fast repolarization time, while **broad-spiking excitatory neurons** tend to have longer trough to peak duration and slower repolarization time. Apart from these feature differences, the cell types tend to differ in firing properties as well.</span>
<span id="cb34-71"><a href="#cb34-71" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb34-72"><a href="#cb34-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-73"><a href="#cb34-73" aria-hidden="true" tabindex="-1"></a><span class="fu">## 1.3 Our research question</span></span>
<span id="cb34-74"><a href="#cb34-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-75"><a href="#cb34-75" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; **Do the waveform features (trough to peak duration and repolarization time) of a neuron predict how often it fires?**</span></span>
<span id="cb34-76"><a href="#cb34-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-77"><a href="#cb34-77" aria-hidden="true" tabindex="-1"></a>From this question, we will model <span class="in">`firing_rate`</span> as a function of <span class="in">`trough_to_peak`</span>, <span class="in">`repolarization_time`</span>, and <span class="in">`depth`</span>. The first two are waveform features that capture the cell-type info, and the <span class="in">`depth`</span> is treated as a control, since the depth of the probe is known to influence baseline firing rates and we want to isolate the effect of waveform shape from other effect.</span>
<span id="cb34-78"><a href="#cb34-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-79"><a href="#cb34-79" aria-hidden="true" tabindex="-1"></a>Therefore, we aim to know in this tutorial that: </span>
<span id="cb34-80"><a href="#cb34-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-81"><a href="#cb34-81" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>Whether and potentially how these three predictors jointly relate to firing rate</span>
<span id="cb34-82"><a href="#cb34-82" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>Whether the assumptions of OLS regression are appropriate here </span>
<span id="cb34-83"><a href="#cb34-83" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>How to interpret and examine these results here (we would also have a small writeup)</span>
<span id="cb34-84"><a href="#cb34-84" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>What alternatives here might also suit for my dataset</span>
<span id="cb34-85"><a href="#cb34-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-86"><a href="#cb34-86" aria-hidden="true" tabindex="-1"></a><span class="fu"># 2. Setup</span></span>
<span id="cb34-87"><a href="#cb34-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-88"><a href="#cb34-88" aria-hidden="true" tabindex="-1"></a><span class="fu">## 2.1 Loading packages</span></span>
<span id="cb34-89"><a href="#cb34-89" aria-hidden="true" tabindex="-1"></a>We will employ pacakges from the **tidyverse** to do plotting and data manipulation and the **easystats** to clean model summaries and effect sizes.</span>
<span id="cb34-90"><a href="#cb34-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-91"><a href="#cb34-91" aria-hidden="true" tabindex="-1"></a>So we frist need to check whether each package is installed and then loads them all. </span>
<span id="cb34-92"><a href="#cb34-92" aria-hidden="true" tabindex="-1"></a><span class="in">```{r packages}</span></span>
<span id="cb34-93"><a href="#cb34-93" aria-hidden="true" tabindex="-1"></a>required_pkgs <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb34-94"><a href="#cb34-94" aria-hidden="true" tabindex="-1"></a>  <span class="st">"tidyverse"</span>,    </span>
<span id="cb34-95"><a href="#cb34-95" aria-hidden="true" tabindex="-1"></a>  <span class="st">"easystats"</span>,     </span>
<span id="cb34-96"><a href="#cb34-96" aria-hidden="true" tabindex="-1"></a>  <span class="st">"performance"</span>,   <span class="co">#check_model</span></span>
<span id="cb34-97"><a href="#cb34-97" aria-hidden="true" tabindex="-1"></a>  <span class="st">"parameters"</span>,    </span>
<span id="cb34-98"><a href="#cb34-98" aria-hidden="true" tabindex="-1"></a>  <span class="st">"see"</span>,          </span>
<span id="cb34-99"><a href="#cb34-99" aria-hidden="true" tabindex="-1"></a>  <span class="st">"correlation"</span>,   </span>
<span id="cb34-100"><a href="#cb34-100" aria-hidden="true" tabindex="-1"></a>  <span class="st">"ggeffects"</span>,     </span>
<span id="cb34-101"><a href="#cb34-101" aria-hidden="true" tabindex="-1"></a>  <span class="st">"gt"</span>,            </span>
<span id="cb34-102"><a href="#cb34-102" aria-hidden="true" tabindex="-1"></a>  <span class="st">"broom"</span>,         </span>
<span id="cb34-103"><a href="#cb34-103" aria-hidden="true" tabindex="-1"></a>  <span class="st">"patchwork"</span>,    </span>
<span id="cb34-104"><a href="#cb34-104" aria-hidden="true" tabindex="-1"></a>  <span class="st">"car"</span>,           </span>
<span id="cb34-105"><a href="#cb34-105" aria-hidden="true" tabindex="-1"></a>  <span class="st">"sandwich"</span>,      </span>
<span id="cb34-106"><a href="#cb34-106" aria-hidden="true" tabindex="-1"></a>  <span class="st">"lmtest"</span>,        </span>
<span id="cb34-107"><a href="#cb34-107" aria-hidden="true" tabindex="-1"></a>  <span class="st">"knitr"</span></span>
<span id="cb34-108"><a href="#cb34-108" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb34-109"><a href="#cb34-109" aria-hidden="true" tabindex="-1"></a><span class="co">#install anything missing</span></span>
<span id="cb34-110"><a href="#cb34-110" aria-hidden="true" tabindex="-1"></a>missing_pkgs <span class="ot">&lt;-</span> <span class="fu">setdiff</span>(required_pkgs, <span class="fu">rownames</span>(<span class="fu">installed.packages</span>()))</span>
<span id="cb34-111"><a href="#cb34-111" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">length</span>(missing_pkgs) <span class="sc">&gt;</span> <span class="dv">0</span>) {</span>
<span id="cb34-112"><a href="#cb34-112" aria-hidden="true" tabindex="-1"></a>  <span class="fu">install.packages</span>(missing_pkgs, <span class="at">repos =</span> <span class="st">"https://cloud.r-project.org"</span>)}</span>
<span id="cb34-113"><a href="#cb34-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-114"><a href="#cb34-114" aria-hidden="true" tabindex="-1"></a><span class="co">#load</span></span>
<span id="cb34-115"><a href="#cb34-115" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(</span>
<span id="cb34-116"><a href="#cb34-116" aria-hidden="true" tabindex="-1"></a>  <span class="fu">invisible</span>(<span class="fu">lapply</span>(required_pkgs, library, <span class="at">character.only =</span> <span class="cn">TRUE</span>))</span>
<span id="cb34-117"><a href="#cb34-117" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb34-118"><a href="#cb34-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-119"><a href="#cb34-119" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">scipen =</span> <span class="dv">999</span>, <span class="at">digits =</span> <span class="dv">4</span>)</span>
<span id="cb34-120"><a href="#cb34-120" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(<span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">12</span>))</span>
<span id="cb34-121"><a href="#cb34-121" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb34-122"><a href="#cb34-122" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-123"><a href="#cb34-123" aria-hidden="true" tabindex="-1"></a><span class="fu">## 2.2 Loading the data</span></span>
<span id="cb34-124"><a href="#cb34-124" aria-hidden="true" tabindex="-1"></a>The data are stored as a CSV file; We need to load it with **read_csv** and have a quick look.</span>
<span id="cb34-125"><a href="#cb34-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-126"><a href="#cb34-126" aria-hidden="true" tabindex="-1"></a><span class="in">```{r load-data}</span></span>
<span id="cb34-127"><a href="#cb34-127" aria-hidden="true" tabindex="-1"></a>fef <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_csv</span>(<span class="st">"data/fef_prelim_metrics.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb34-128"><a href="#cb34-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-129"><a href="#cb34-129" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(fef)</span>
<span id="cb34-130"><a href="#cb34-130" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb34-131"><a href="#cb34-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-132"><a href="#cb34-132" aria-hidden="true" tabindex="-1"></a>We can do some sanity checks:</span>
<span id="cb34-133"><a href="#cb34-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-134"><a href="#cb34-134" aria-hidden="true" tabindex="-1"></a><span class="in">```{r data-sanity}</span></span>
<span id="cb34-135"><a href="#cb34-135" aria-hidden="true" tabindex="-1"></a><span class="co">#dimension</span></span>
<span id="cb34-136"><a href="#cb34-136" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(fef)</span>
<span id="cb34-137"><a href="#cb34-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-138"><a href="#cb34-138" aria-hidden="true" tabindex="-1"></a><span class="co">#number of units we have </span></span>
<span id="cb34-139"><a href="#cb34-139" aria-hidden="true" tabindex="-1"></a>fef <span class="sc">|&gt;</span></span>
<span id="cb34-140"><a href="#cb34-140" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(session_id, <span class="at">name =</span> <span class="st">"n_units"</span>) <span class="sc">|&gt;</span></span>
<span id="cb34-141"><a href="#cb34-141" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="at">caption =</span> <span class="st">"Number of units recorded per session."</span>)</span>
<span id="cb34-142"><a href="#cb34-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-143"><a href="#cb34-143" aria-hidden="true" tabindex="-1"></a><span class="co">#check missing values; (normally due to the data traits we assume none)</span></span>
<span id="cb34-144"><a href="#cb34-144" aria-hidden="true" tabindex="-1"></a><span class="fu">colSums</span>(<span class="fu">is.na</span>(fef))</span>
<span id="cb34-145"><a href="#cb34-145" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb34-146"><a href="#cb34-146" aria-hidden="true" tabindex="-1"></a>::: {.callout-note}</span>
<span id="cb34-147"><a href="#cb34-147" aria-hidden="true" tabindex="-1"></a><span class="fu">## About the data</span></span>
<span id="cb34-148"><a href="#cb34-148" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>So we confirmed that we  have **316 units** across **8 sessions**</span>
<span id="cb34-149"><a href="#cb34-149" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The number of units per session ranges is around 30-50 unit</span>
<span id="cb34-150"><a href="#cb34-150" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>There are no missing values </span>
<span id="cb34-151"><a href="#cb34-151" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb34-152"><a href="#cb34-152" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-153"><a href="#cb34-153" aria-hidden="true" tabindex="-1"></a><span class="fu"># 3. Exploratory Data Analysis</span></span>
<span id="cb34-154"><a href="#cb34-154" aria-hidden="true" tabindex="-1"></a>Before fitting any model, we can first see the  distributions of each variable and pairwise relationships so we can have an understanding of how we can model it later :)</span>
<span id="cb34-155"><a href="#cb34-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-156"><a href="#cb34-156" aria-hidden="true" tabindex="-1"></a><span class="fu">## 3.1 Distributions of the features</span></span>
<span id="cb34-157"><a href="#cb34-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-158"><a href="#cb34-158" aria-hidden="true" tabindex="-1"></a>We focus on the four variables: the outcome **firing_rate** and the three predictors **trough_to_peak**, **repolarization_time**, and **depth**.</span>
<span id="cb34-159"><a href="#cb34-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-160"><a href="#cb34-160" aria-hidden="true" tabindex="-1"></a><span class="in">```{r distributions}</span></span>
<span id="cb34-161"><a href="#cb34-161" aria-hidden="true" tabindex="-1"></a>fef_long <span class="ot">&lt;-</span> fef <span class="sc">|&gt;</span></span>
<span id="cb34-162"><a href="#cb34-162" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(firing_rate, trough_to_peak, repolarization_time, depth) <span class="sc">|&gt;</span></span>
<span id="cb34-163"><a href="#cb34-163" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="fu">everything</span>(), <span class="at">names_to =</span> <span class="st">"variable"</span>, <span class="at">values_to =</span> <span class="st">"value"</span>)</span>
<span id="cb34-164"><a href="#cb34-164" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-165"><a href="#cb34-165" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(fef_long, <span class="fu">aes</span>(<span class="at">x =</span> value)) <span class="sc">+</span></span>
<span id="cb34-166"><a href="#cb34-166" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">30</span>, <span class="at">fill =</span> <span class="st">"#1f8a8c"</span>, <span class="at">color =</span> <span class="st">"white"</span>, <span class="at">alpha =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb34-167"><a href="#cb34-167" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> variable, <span class="at">scales =</span> <span class="st">"free"</span>, <span class="at">ncol =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb34-168"><a href="#cb34-168" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb34-169"><a href="#cb34-169" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">"Number of units"</span>,</span>
<span id="cb34-170"><a href="#cb34-170" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Distributions of features"</span></span>
<span id="cb34-171"><a href="#cb34-171" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb34-172"><a href="#cb34-172" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb34-173"><a href="#cb34-173" aria-hidden="true" tabindex="-1"></a>::: {.callout-note}</span>
<span id="cb34-174"><a href="#cb34-174" aria-hidden="true" tabindex="-1"></a><span class="fu">## What we found</span></span>
<span id="cb34-175"><a href="#cb34-175" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**`firing_rate` is strongly right-skewed.** </span>
<span id="cb34-176"><a href="#cb34-176" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**`trough_to_peak` is bimodal.** This suggest there are two potential cell types here as we mentioned earlier.</span>
<span id="cb34-177"><a href="#cb34-177" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb34-178"><a href="#cb34-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-179"><a href="#cb34-179" aria-hidden="true" tabindex="-1"></a><span class="fu">## 3.2 Correlations</span></span>
<span id="cb34-180"><a href="#cb34-180" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-181"><a href="#cb34-181" aria-hidden="true" tabindex="-1"></a>We can first check how the predictors may correlate with each other by having a correlation matrix since multiple regression does not expect predictors to be so tightly correlated (but could have some slight correlations).</span>
<span id="cb34-182"><a href="#cb34-182" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-183"><a href="#cb34-183" aria-hidden="true" tabindex="-1"></a><span class="in">```{r corr-matrix}</span></span>
<span id="cb34-184"><a href="#cb34-184" aria-hidden="true" tabindex="-1"></a>fef <span class="sc">|&gt;</span></span>
<span id="cb34-185"><a href="#cb34-185" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(firing_rate, trough_to_peak, repolarization_time, depth) <span class="sc">|&gt;</span></span>
<span id="cb34-186"><a href="#cb34-186" aria-hidden="true" tabindex="-1"></a>  correlation<span class="sc">::</span><span class="fu">correlation</span>() <span class="sc">|&gt;</span></span>
<span id="cb34-187"><a href="#cb34-187" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>(<span class="at">redundant =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb34-188"><a href="#cb34-188" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">2</span>, <span class="at">caption =</span> <span class="st">"Pairwise Pearson correlations."</span>)</span>
<span id="cb34-189"><a href="#cb34-189" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb34-190"><a href="#cb34-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-191"><a href="#cb34-191" aria-hidden="true" tabindex="-1"></a>::: {.callout-note}</span>
<span id="cb34-192"><a href="#cb34-192" aria-hidden="true" tabindex="-1"></a><span class="fu">## Correlatons</span></span>
<span id="cb34-193"><a href="#cb34-193" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**All of the three predictors have some correlations with the outcome**, with repolarization time the strongest, but the extent is moderate, so we could see each of the predictor contribute to some correlation with the outcome.</span>
<span id="cb34-194"><a href="#cb34-194" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**The two waveform-shape variables correlate with each other with moderately strong  r = 0.53**, which is biologically reasonable. </span>
<span id="cb34-195"><a href="#cb34-195" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Depth** is a great control here since it weakly correlate with the two waveform features </span>
<span id="cb34-196"><a href="#cb34-196" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb34-197"><a href="#cb34-197" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-198"><a href="#cb34-198" aria-hidden="true" tabindex="-1"></a><span class="fu">## 3.3 Bivariate relationships with the outcome</span></span>
<span id="cb34-199"><a href="#cb34-199" aria-hidden="true" tabindex="-1"></a>We can see from the scatterplot to show whether we can see linear patterns.</span>
<span id="cb34-200"><a href="#cb34-200" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-201"><a href="#cb34-201" aria-hidden="true" tabindex="-1"></a><span class="in">```{r scatterplots, fig.height=4}</span></span>
<span id="cb34-202"><a href="#cb34-202" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(fef, <span class="fu">aes</span>(trough_to_peak, firing_rate)) <span class="sc">+</span></span>
<span id="cb34-203"><a href="#cb34-203" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">color =</span> <span class="st">"#1f8a8c"</span>) <span class="sc">+</span></span>
<span id="cb34-204"><a href="#cb34-204" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">"#d97706"</span>) <span class="sc">+</span></span>
<span id="cb34-205"><a href="#cb34-205" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Trough-to-peak (ms)"</span>, <span class="at">y =</span> <span class="st">"Firing rate (Hz)"</span>)</span>
<span id="cb34-206"><a href="#cb34-206" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-207"><a href="#cb34-207" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(fef, <span class="fu">aes</span>(repolarization_time, firing_rate)) <span class="sc">+</span></span>
<span id="cb34-208"><a href="#cb34-208" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">color =</span> <span class="st">"#1f8a8c"</span>) <span class="sc">+</span></span>
<span id="cb34-209"><a href="#cb34-209" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">"#d97706"</span>) <span class="sc">+</span></span>
<span id="cb34-210"><a href="#cb34-210" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Repolarization time (ms)"</span>, <span class="at">y =</span> <span class="st">"Firing rate (Hz)"</span>)</span>
<span id="cb34-211"><a href="#cb34-211" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-212"><a href="#cb34-212" aria-hidden="true" tabindex="-1"></a>p3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(fef, <span class="fu">aes</span>(depth, firing_rate)) <span class="sc">+</span></span>
<span id="cb34-213"><a href="#cb34-213" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">color =</span> <span class="st">"#1f8a8c"</span>) <span class="sc">+</span></span>
<span id="cb34-214"><a href="#cb34-214" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">"#d97706"</span>) <span class="sc">+</span></span>
<span id="cb34-215"><a href="#cb34-215" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Depth (µm)"</span>, <span class="at">y =</span> <span class="st">"Firing rate (Hz)"</span>)</span>
<span id="cb34-216"><a href="#cb34-216" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-217"><a href="#cb34-217" aria-hidden="true" tabindex="-1"></a>(p1 <span class="sc">|</span> p2 <span class="sc">|</span> p3)</span>
<span id="cb34-218"><a href="#cb34-218" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb34-219"><a href="#cb34-219" aria-hidden="true" tabindex="-1"></a>::: {.callout-note}</span>
<span id="cb34-220"><a href="#cb34-220" aria-hidden="true" tabindex="-1"></a><span class="fu">## In the scatterplot</span></span>
<span id="cb34-221"><a href="#cb34-221" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**The right-skew is very strong.** So we can see the `firing_rate` points are most near the bottom and a few of them at very hight herz,and this non-constant feature suggests that **homoskedasticity** (the assumption that residual variance is constant) would not true. We need to address it later. </span>
<span id="cb34-222"><a href="#cb34-222" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb34-223"><a href="#cb34-223" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-224"><a href="#cb34-224" aria-hidden="true" tabindex="-1"></a><span class="fu"># 4. Fitting the multiple regression</span></span>
<span id="cb34-225"><a href="#cb34-225" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-226"><a href="#cb34-226" aria-hidden="true" tabindex="-1"></a><span class="fu">## 4.1 The model we will fit</span></span>
<span id="cb34-227"><a href="#cb34-227" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-228"><a href="#cb34-228" aria-hidden="true" tabindex="-1"></a>Specifically, according to our plan, the model is like this: </span>
<span id="cb34-229"><a href="#cb34-229" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb34-230"><a href="#cb34-230" aria-hidden="true" tabindex="-1"></a>\text{firing<span class="sc">\_</span>rate} = \beta_0 + \beta_1\,\text{trough<span class="sc">\_</span>to<span class="sc">\_</span>peak} + \beta_2\,\text{repolarization<span class="sc">\_</span>time} + \beta_3\,\text{depth} + \varepsilon.</span>
<span id="cb34-231"><a href="#cb34-231" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb34-232"><a href="#cb34-232" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-233"><a href="#cb34-233" aria-hidden="true" tabindex="-1"></a><span class="fu">## 4.2 Fitting the model</span></span>
<span id="cb34-234"><a href="#cb34-234" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-235"><a href="#cb34-235" aria-hidden="true" tabindex="-1"></a>We fit a linear model with <span class="in">`lm()`</span>.</span>
<span id="cb34-236"><a href="#cb34-236" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-237"><a href="#cb34-237" aria-hidden="true" tabindex="-1"></a><span class="in">```{r fit-model}</span></span>
<span id="cb34-238"><a href="#cb34-238" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(firing_rate <span class="sc">~</span> trough_to_peak <span class="sc">+</span> repolarization_time <span class="sc">+</span> depth,</span>
<span id="cb34-239"><a href="#cb34-239" aria-hidden="true" tabindex="-1"></a>          <span class="at">data =</span> fef)</span>
<span id="cb34-240"><a href="#cb34-240" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-241"><a href="#cb34-241" aria-hidden="true" tabindex="-1"></a>fit</span>
<span id="cb34-242"><a href="#cb34-242" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb34-243"><a href="#cb34-243" aria-hidden="true" tabindex="-1"></a><span class="fu">## 4.3 Output</span></span>
<span id="cb34-244"><a href="#cb34-244" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-245"><a href="#cb34-245" aria-hidden="true" tabindex="-1"></a>We can use <span class="in">`summary(fit)`</span> to see the summarizing output. </span>
<span id="cb34-246"><a href="#cb34-246" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-247"><a href="#cb34-247" aria-hidden="true" tabindex="-1"></a><span class="in">```{r model-summary}</span></span>
<span id="cb34-248"><a href="#cb34-248" aria-hidden="true" tabindex="-1"></a>parameters<span class="sc">::</span><span class="fu">model_parameters</span>(fit) <span class="sc">|&gt;</span></span>
<span id="cb34-249"><a href="#cb34-249" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>()</span>
<span id="cb34-250"><a href="#cb34-250" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb34-251"><a href="#cb34-251" aria-hidden="true" tabindex="-1"></a>Each row of this table corresponds to one coefficient.</span>
<span id="cb34-252"><a href="#cb34-252" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-253"><a href="#cb34-253" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Coefficient** </span>
<span id="cb34-254"><a href="#cb34-254" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**CI low / CI high** — the 95% confidence interval </span>
<span id="cb34-255"><a href="#cb34-255" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**t** — coefficient divided by its standard error.</span>
<span id="cb34-256"><a href="#cb34-256" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**p** — the p-value for the null hypothesis </span>
<span id="cb34-257"><a href="#cb34-257" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-258"><a href="#cb34-258" aria-hidden="true" tabindex="-1"></a>::: {.callout-important}</span>
<span id="cb34-259"><a href="#cb34-259" aria-hidden="true" tabindex="-1"></a><span class="fu">## What can we read from this model summary about the question we want to ask</span></span>
<span id="cb34-260"><a href="#cb34-260" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-261"><a href="#cb34-261" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**`trough_to_peak`** We can see from the coefficient and p value that if we control <span class="in">`repolarization_time`</span> and <span class="in">`depth`</span>, then one millisecond of increase in trough-to-peak duration provides no additional information about firing rate. The 95% CI <span class="co">[</span><span class="ot">−4.08, 4.71</span><span class="co">]</span> easily includes zero.</span>
<span id="cb34-262"><a href="#cb34-262" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-263"><a href="#cb34-263" aria-hidden="true" tabindex="-1"></a>**`repolarization_time`** Repolarization time shows the dominant effect. So we know that across the full observed range of repolarization time, predicted firing rate moves by roughly $35.96 \times 0.5 \approx 18$ Hz, while holding the other predictors constant.</span>
<span id="cb34-264"><a href="#cb34-264" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-265"><a href="#cb34-265" aria-hidden="true" tabindex="-1"></a>**Now from the summary we know that waveform shape predicts firing rate, but major predictive factor is specifically by `repolarization_time` instead of `trough_to_peak`. Depth contributes a small additional effect.**</span>
<span id="cb34-266"><a href="#cb34-266" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb34-267"><a href="#cb34-267" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-268"><a href="#cb34-268" aria-hidden="true" tabindex="-1"></a><span class="fu"># 5. Checking Assumptions</span></span>
<span id="cb34-269"><a href="#cb34-269" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-270"><a href="#cb34-270" aria-hidden="true" tabindex="-1"></a>We need to check the assumptions behind the OLS multiple regression model. The four assumptions are:</span>
<span id="cb34-271"><a href="#cb34-271" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-272"><a href="#cb34-272" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**Linearity** — the relationship between each predictor and the outcome is linear.</span>
<span id="cb34-273"><a href="#cb34-273" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**Independence of errors** — residuals from one observation are not correlated with residuals from another.</span>
<span id="cb34-274"><a href="#cb34-274" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**Normality of residuals** — the residuals are roughly normally distributed.</span>
<span id="cb34-275"><a href="#cb34-275" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>**Homoscedasticity** — residual variance is constant </span>
<span id="cb34-276"><a href="#cb34-276" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-277"><a href="#cb34-277" aria-hidden="true" tabindex="-1"></a>Other things like multicollinearity could also be checked here </span>
<span id="cb34-278"><a href="#cb34-278" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-279"><a href="#cb34-279" aria-hidden="true" tabindex="-1"></a><span class="fu">## 5.1 Plotting</span></span>
<span id="cb34-280"><a href="#cb34-280" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-281"><a href="#cb34-281" aria-hidden="true" tabindex="-1"></a><span class="in">```{r check-model, fig.height=8, fig.width=9}</span></span>
<span id="cb34-282"><a href="#cb34-282" aria-hidden="true" tabindex="-1"></a>performance<span class="sc">::</span><span class="fu">check_model</span>(fit)</span>
<span id="cb34-283"><a href="#cb34-283" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb34-284"><a href="#cb34-284" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-285"><a href="#cb34-285" aria-hidden="true" tabindex="-1"></a>::: {.callout-important}</span>
<span id="cb34-286"><a href="#cb34-286" aria-hidden="true" tabindex="-1"></a>Walking through each assumption panel:</span>
<span id="cb34-287"><a href="#cb34-287" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-288"><a href="#cb34-288" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Posterior predictive check** The green observed density is shifted right and get narrower than the blue density predicted by the model. The Gaussian assumption is a poor fit to this positive and  right-skewed outcome. So this suggest that we need to transform <span class="in">`firing_rate`</span>later to handle it. </span>
<span id="cb34-289"><a href="#cb34-289" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Linearity**   Linearity itself is reasonable. </span>
<span id="cb34-290"><a href="#cb34-290" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Homogeneity of variance** Residual variance grows with the fitted value, so this show a very clear version of **heteroskedasticity** and is exactly matched what we thought may have from the right-skew in section 3.</span>
<span id="cb34-291"><a href="#cb34-291" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Influential observations** All points sit inside the Cook's-distance contours.</span>
<span id="cb34-292"><a href="#cb34-292" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Collinearity** All three predictors land in the "Low (&lt; 5)" zone. Multicollinearity is not appearing to be a problem here. </span>
<span id="cb34-293"><a href="#cb34-293" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Normality of residuals**  The right tail have an upward trend. This is the predictable consequence of a right-skewed outcome and should improve substantially after a log transform.</span>
<span id="cb34-294"><a href="#cb34-294" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb34-295"><a href="#cb34-295" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-296"><a href="#cb34-296" aria-hidden="true" tabindex="-1"></a><span class="fu">## 5.2 Multicollinearity </span></span>
<span id="cb34-297"><a href="#cb34-297" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-298"><a href="#cb34-298" aria-hidden="true" tabindex="-1"></a><span class="in">```{r vif}</span></span>
<span id="cb34-299"><a href="#cb34-299" aria-hidden="true" tabindex="-1"></a>performance<span class="sc">::</span><span class="fu">check_collinearity</span>(fit)</span>
<span id="cb34-300"><a href="#cb34-300" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb34-301"><a href="#cb34-301" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-302"><a href="#cb34-302" aria-hidden="true" tabindex="-1"></a>::: {.callout-important}</span>
<span id="cb34-303"><a href="#cb34-303" aria-hidden="true" tabindex="-1"></a>The VIF are all smaller than 5, all three predictors are inside the safe zone, so we dont wrroy about the multicollinearity problem here.</span>
<span id="cb34-304"><a href="#cb34-304" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb34-305"><a href="#cb34-305" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-306"><a href="#cb34-306" aria-hidden="true" tabindex="-1"></a><span class="fu">## 5.3 Heteroskedasticity</span></span>
<span id="cb34-307"><a href="#cb34-307" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-308"><a href="#cb34-308" aria-hidden="true" tabindex="-1"></a><span class="in">```{r het-test}</span></span>
<span id="cb34-309"><a href="#cb34-309" aria-hidden="true" tabindex="-1"></a>performance<span class="sc">::</span><span class="fu">check_heteroscedasticity</span>(fit)</span>
<span id="cb34-310"><a href="#cb34-310" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb34-311"><a href="#cb34-311" aria-hidden="true" tabindex="-1"></a>This mataching the observations above. </span>
<span id="cb34-312"><a href="#cb34-312" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-313"><a href="#cb34-313" aria-hidden="true" tabindex="-1"></a><span class="fu">## 5.4 Normality of residuals</span></span>
<span id="cb34-314"><a href="#cb34-314" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-315"><a href="#cb34-315" aria-hidden="true" tabindex="-1"></a><span class="in">```{r norm-test}</span></span>
<span id="cb34-316"><a href="#cb34-316" aria-hidden="true" tabindex="-1"></a>performance<span class="sc">::</span><span class="fu">check_normality</span>(fit)</span>
<span id="cb34-317"><a href="#cb34-317" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb34-318"><a href="#cb34-318" aria-hidden="true" tabindex="-1"></a>This is matching the observations above. </span>
<span id="cb34-319"><a href="#cb34-319" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-320"><a href="#cb34-320" aria-hidden="true" tabindex="-1"></a><span class="fu">## 5.5 Independence</span></span>
<span id="cb34-321"><a href="#cb34-321" aria-hidden="true" tabindex="-1"></a>In this dataset, the 316 units come from only **8 sessions**. Units recorded in the same session share an animal, an electrode position, and a recording day, so their residuals are very likely correlated.The independence assumption is likely violated. </span>
<span id="cb34-322"><a href="#cb34-322" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-323"><a href="#cb34-323" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-324"><a href="#cb34-324" aria-hidden="true" tabindex="-1"></a>::: {.callout-note}</span>
<span id="cb34-325"><a href="#cb34-325" aria-hidden="true" tabindex="-1"></a><span class="fu">## Summary:</span></span>
<span id="cb34-326"><a href="#cb34-326" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-327"><a href="#cb34-327" aria-hidden="true" tabindex="-1"></a>The checking assumptions show three problems</span>
<span id="cb34-328"><a href="#cb34-328" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Homoscedasticity** Violated,  Heteroscedasticity detected (p &lt; .001) </span>
<span id="cb34-329"><a href="#cb34-329" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Normality of residuals** Violated, Shapiro–Wilk p &lt; .001 </span>
<span id="cb34-330"><a href="#cb34-330" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Independence** Violated,316 units come from only 8 sessions </span>
<span id="cb34-331"><a href="#cb34-331" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-332"><a href="#cb34-332" aria-hidden="true" tabindex="-1"></a>The first two violations is of the right-skewed outcome. A log transform of <span class="in">`firing_rate`</span> should largely fix them.</span>
<span id="cb34-333"><a href="#cb34-333" aria-hidden="true" tabindex="-1"></a>The third (independence) variable, we  address it with **HC3 cluster-robust standard errors**, which keep the OLS point estimates but recompute the standard errors to acknowledge within-session correlation.</span>
<span id="cb34-334"><a href="#cb34-334" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb34-335"><a href="#cb34-335" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-336"><a href="#cb34-336" aria-hidden="true" tabindex="-1"></a><span class="fu"># 6. Fixing the Violations</span></span>
<span id="cb34-337"><a href="#cb34-337" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-338"><a href="#cb34-338" aria-hidden="true" tabindex="-1"></a>So we can the assumptions violated for **heteroscedasticity** and **non-normal residuals**. We now need to do a log transform for th firing rates to solve this problem. </span>
<span id="cb34-339"><a href="#cb34-339" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-340"><a href="#cb34-340" aria-hidden="true" tabindex="-1"></a><span class="fu">## 6.1 Log-transform the outcome</span></span>
<span id="cb34-341"><a href="#cb34-341" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-342"><a href="#cb34-342" aria-hidden="true" tabindex="-1"></a>Firing rates are right-skewed, so <span class="in">`log()`</span> should stablizes variance.</span>
<span id="cb34-343"><a href="#cb34-343" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-346"><a href="#cb34-346" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb34-347"><a href="#cb34-347" aria-hidden="true" tabindex="-1"></a>m_log <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(firing_rate) <span class="sc">~</span> trough_to_peak <span class="sc">+</span> repolarization_time <span class="sc">+</span> depth,</span>
<span id="cb34-348"><a href="#cb34-348" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> fef)</span>
<span id="cb34-349"><a href="#cb34-349" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-350"><a href="#cb34-350" aria-hidden="true" tabindex="-1"></a><span class="fu">check_heteroscedasticity</span>(m_log)</span>
<span id="cb34-351"><a href="#cb34-351" aria-hidden="true" tabindex="-1"></a><span class="fu">check_normality</span>(m_log)</span>
<span id="cb34-352"><a href="#cb34-352" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb34-353"><a href="#cb34-353" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-356"><a href="#cb34-356" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb34-357"><a href="#cb34-357" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-width: 8</span></span>
<span id="cb34-358"><a href="#cb34-358" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-height: 5</span></span>
<span id="cb34-359"><a href="#cb34-359" aria-hidden="true" tabindex="-1"></a><span class="fu">check_model</span>(m_log, <span class="at">check =</span> <span class="fu">c</span>(<span class="st">"homogeneity"</span>, <span class="st">"qq"</span>))</span>
<span id="cb34-360"><a href="#cb34-360" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb34-361"><a href="#cb34-361" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-362"><a href="#cb34-362" aria-hidden="true" tabindex="-1"></a><span class="fu">## 6.2 Cluster-robust SEs</span></span>
<span id="cb34-363"><a href="#cb34-363" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-364"><a href="#cb34-364" aria-hidden="true" tabindex="-1"></a>Units are nested in 8 sessions, so residuals aren't independent. So we use HC3 to improve it.</span>
<span id="cb34-365"><a href="#cb34-365" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-368"><a href="#cb34-368" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb34-369"><a href="#cb34-369" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sandwich); <span class="fu">library</span>(lmtest)</span>
<span id="cb34-370"><a href="#cb34-370" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-371"><a href="#cb34-371" aria-hidden="true" tabindex="-1"></a><span class="fu">coeftest</span>(m_log, <span class="at">vcov =</span> <span class="fu">vcovCL</span>(m_log, <span class="at">cluster =</span> <span class="sc">~</span> session_id, <span class="at">type =</span> <span class="st">"HC3"</span>))</span>
<span id="cb34-372"><a href="#cb34-372" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb34-373"><a href="#cb34-373" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-374"><a href="#cb34-374" aria-hidden="true" tabindex="-1"></a>::: {.callout-note}</span>
<span id="cb34-375"><a href="#cb34-375" aria-hidden="true" tabindex="-1"></a>**Summary of the Violation Handle**</span>
<span id="cb34-376"><a href="#cb34-376" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-377"><a href="#cb34-377" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Non-normality** — So we do the Log-transforming of the <span class="in">`firing_rate`</span>, and we could see a lot of improvements. The QQ plot now tracks the reference line much better that previously, and although the violation check still returns p = .031, we could see the deviations are minor at this stage, so we largely fix this violations.</span>
<span id="cb34-378"><a href="#cb34-378" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-379"><a href="#cb34-379" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Heteroscedasticity** — We can see a lot of improvements  after the log transform but we are not fully solve the problem of hereoscedasticity since we got (p = .004). I think the good point here is that the HC3 would provide robust inference even when residual variance isn't constant, so we might have less worry on this. But in the future, we might need to think other way to transfor firing rates to solve this issue entirely. </span>
<span id="cb34-380"><a href="#cb34-380" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-381"><a href="#cb34-381" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Non-independence (8 sessions)** — We address this issue by clustering SE on <span class="in">`session_id`</span>. Now we can see <span class="in">`repolarization_time`</span> and <span class="in">`depth`</span> remain highly significant and <span class="in">`trough_to_peak`</span> stays non-significant, which is matching the original OLS conclusion.</span>
<span id="cb34-382"><a href="#cb34-382" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb34-383"><a href="#cb34-383" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-384"><a href="#cb34-384" aria-hidden="true" tabindex="-1"></a><span class="fu"># 7. Effect Size and the Interpretation</span></span>
<span id="cb34-385"><a href="#cb34-385" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-386"><a href="#cb34-386" aria-hidden="true" tabindex="-1"></a><span class="fu">## 7.1 Model fit</span></span>
<span id="cb34-387"><a href="#cb34-387" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-390"><a href="#cb34-390" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb34-391"><a href="#cb34-391" aria-hidden="true" tabindex="-1"></a><span class="fu">r2</span>(m_log)</span>
<span id="cb34-392"><a href="#cb34-392" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb34-393"><a href="#cb34-393" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-394"><a href="#cb34-394" aria-hidden="true" tabindex="-1"></a><span class="fu">## 7.2 Standardized coefficients</span></span>
<span id="cb34-395"><a href="#cb34-395" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-398"><a href="#cb34-398" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb34-399"><a href="#cb34-399" aria-hidden="true" tabindex="-1"></a><span class="fu">parameters</span>(m_log, <span class="at">standardize =</span> <span class="st">"refit"</span>)</span>
<span id="cb34-400"><a href="#cb34-400" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb34-401"><a href="#cb34-401" aria-hidden="true" tabindex="-1"></a><span class="fu">## 7.3 Partial effect sizes</span></span>
<span id="cb34-402"><a href="#cb34-402" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-405"><a href="#cb34-405" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb34-406"><a href="#cb34-406" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(effectsize)</span>
<span id="cb34-407"><a href="#cb34-407" aria-hidden="true" tabindex="-1"></a><span class="fu">eta_squared</span>(car<span class="sc">::</span><span class="fu">Anova</span>(m_log, <span class="at">type =</span> <span class="dv">2</span>), <span class="at">partial =</span> <span class="cn">TRUE</span>)</span>
<span id="cb34-408"><a href="#cb34-408" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb34-409"><a href="#cb34-409" aria-hidden="true" tabindex="-1"></a>::: {.callout-note}</span>
<span id="cb34-410"><a href="#cb34-410" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Overall fit** — The three predictors jointly explain **29% of the variance** in log firing rate. This rate is actually pretty solide for neuron waveforms due to the noisy nature of the extracellular recordings and also we only have three waveform features in the model. </span>
<span id="cb34-411"><a href="#cb34-411" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Which predictor matters most?** </span>
<span id="cb34-412"><a href="#cb34-412" aria-hidden="true" tabindex="-1"></a><span class="ss">  - </span><span class="in">`repolarization_time`</span>: β = 0.17, $\eta_p^2$ = .14, Now we can see the repolarization has the  **large** effect compared to the medium effect by depth and negligible effect from trough to peak duration. </span>
<span id="cb34-413"><a href="#cb34-413" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Now we can see that longer repolarization times predict higher firing rates; and deeper units fire at lower rates. </span>
<span id="cb34-414"><a href="#cb34-414" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb34-415"><a href="#cb34-415" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-416"><a href="#cb34-416" aria-hidden="true" tabindex="-1"></a><span class="fu"># 8. Visualizing Partial Effects</span></span>
<span id="cb34-417"><a href="#cb34-417" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-418"><a href="#cb34-418" aria-hidden="true" tabindex="-1"></a><span class="fu">## 8.1 Predicted firing rate vs. each predictor</span></span>
<span id="cb34-419"><a href="#cb34-419" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-422"><a href="#cb34-422" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb34-423"><a href="#cb34-423" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-width: 10</span></span>
<span id="cb34-424"><a href="#cb34-424" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-height: 4</span></span>
<span id="cb34-425"><a href="#cb34-425" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggeffects)</span>
<span id="cb34-426"><a href="#cb34-426" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-427"><a href="#cb34-427" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">plot</span>(<span class="fu">predict_response</span>(m_log, <span class="st">"trough_to_peak"</span>)) <span class="sc">+</span></span>
<span id="cb34-428"><a href="#cb34-428" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Trough-to-peak"</span>, <span class="at">y =</span> <span class="st">"Predicted firing rate (Hz)"</span>)</span>
<span id="cb34-429"><a href="#cb34-429" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-430"><a href="#cb34-430" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">plot</span>(<span class="fu">predict_response</span>(m_log, <span class="st">"repolarization_time"</span>)) <span class="sc">+</span></span>
<span id="cb34-431"><a href="#cb34-431" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Repolarization time"</span>, <span class="at">y =</span> <span class="cn">NULL</span>)</span>
<span id="cb34-432"><a href="#cb34-432" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-433"><a href="#cb34-433" aria-hidden="true" tabindex="-1"></a>p3 <span class="ot">&lt;-</span> <span class="fu">plot</span>(<span class="fu">predict_response</span>(m_log, <span class="st">"depth"</span>)) <span class="sc">+</span></span>
<span id="cb34-434"><a href="#cb34-434" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Depth"</span>, <span class="at">y =</span> <span class="cn">NULL</span>)</span>
<span id="cb34-435"><a href="#cb34-435" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-436"><a href="#cb34-436" aria-hidden="true" tabindex="-1"></a>p1 <span class="sc">+</span> p2 <span class="sc">+</span> p3</span>
<span id="cb34-437"><a href="#cb34-437" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb34-438"><a href="#cb34-438" aria-hidden="true" tabindex="-1"></a>::: {.callout-important}</span>
<span id="cb34-439"><a href="#cb34-439" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-440"><a href="#cb34-440" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Trough-to-peak (left)** — The line slopes upward, but the CI band is wide enough,so the effect is statistically not very certain here.</span>
<span id="cb34-441"><a href="#cb34-441" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-442"><a href="#cb34-442" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Repolarization time (middle)** We can see a steep upward curve with a tight CI. We can see the predicted firing rate rises from from ~3 Hz at the shortest repolarization times to ~30 Hz at the longest across the observed range. This is the dominant predictor.</span>
<span id="cb34-443"><a href="#cb34-443" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-444"><a href="#cb34-444" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Depth (right)** — We can see a clear downward slope, it shows a real but smaller effect than repolarization time.</span>
<span id="cb34-445"><a href="#cb34-445" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb34-446"><a href="#cb34-446" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-447"><a href="#cb34-447" aria-hidden="true" tabindex="-1"></a><span class="fu"># 9. Summary and Discussion</span></span>
<span id="cb34-448"><a href="#cb34-448" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-449"><a href="#cb34-449" aria-hidden="true" tabindex="-1"></a><span class="fu">## 9.1 Summary</span></span>
<span id="cb34-450"><a href="#cb34-450" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-451"><a href="#cb34-451" aria-hidden="true" tabindex="-1"></a>Across 316 FEF units, three features jointly explained **29% of the variance** in firing rate (with the log-transform):</span>
<span id="cb34-452"><a href="#cb34-452" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-453"><a href="#cb34-453" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Repolarization time** is the dominant predictor, so that means that the units with longer repolarization would fired faster.</span>
<span id="cb34-454"><a href="#cb34-454" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**depth of the elerode** had a smaller negative effect </span>
<span id="cb34-455"><a href="#cb34-455" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Trough-to-peak duration** was non-significant once the other features were controlled, even though it correlated moderately with firing rate. </span>
<span id="cb34-456"><a href="#cb34-456" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-457"><a href="#cb34-457" aria-hidden="true" tabindex="-1"></a>So answering the question is that the repolarization time, compared to the trough to peak duration, is a greater predictive factor of how often the neuron fires. </span>
<span id="cb34-458"><a href="#cb34-458" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-459"><a href="#cb34-459" aria-hidden="true" tabindex="-1"></a><span class="fu">## 9.2 When is multiple regression the right tool?</span></span>
<span id="cb34-460"><a href="#cb34-460" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-461"><a href="#cb34-461" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The outcome is continuous</span>
<span id="cb34-462"><a href="#cb34-462" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>When we have several predictors and want to know each one's *unique* contribution</span>
<span id="cb34-463"><a href="#cb34-463" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Observations are roughly independent</span>
<span id="cb34-464"><a href="#cb34-464" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb34-465"><a href="#cb34-465" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-466"><a href="#cb34-466" aria-hidden="true" tabindex="-1"></a><span class="fu">## 9.3 Some alternatives</span></span>
<span id="cb34-467"><a href="#cb34-467" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-468"><a href="#cb34-468" aria-hidden="true" tabindex="-1"></a>For this dataset specifically, now we realized that a **mixed-effects model** with a random intercept by <span class="in">`session_id`</span> would be the more appropriate and reasonable model fit here, since it would estimate session-level variability directly.</span>
<span id="cb34-469"><a href="#cb34-469" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-470"><a href="#cb34-470" aria-hidden="true" tabindex="-1"></a><span class="fu">## 9.4 </span></span>
<span id="cb34-471"><a href="#cb34-471" aria-hidden="true" tabindex="-1"></a>::: {.callout-important}</span>
<span id="cb34-472"><a href="#cb34-472" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Thank you for walking through this tutorial with me! And thank you Suyog for letting me have a chance to do such tutorial, it makes me explore new things and actually thinking more how I may use Quarto website for other things!</span>
<span id="cb34-473"><a href="#cb34-473" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb34-474"><a href="#cb34-474" aria-hidden="true" tabindex="-1"></a>------------------------------------------------------------------------</span>
<span id="cb34-475"><a href="#cb34-475" aria-hidden="true" tabindex="-1"></a></span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>PSY 504 Final Project · Yujingai (Emmy) Shi · Spring 2026</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Built with <a href="https://quarto.org">Quarto</a></p>
</div>
  </div>
</footer>




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>